{{- if .Values.createExamplePolicies }}
{{- range .Values.examplePolicies }}
---
apiVersion: rightsizer.io/v1alpha1
kind: RightSizerPolicy
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "right-sizer.labels" $ | nindent 4 }}
    app.kubernetes.io/component: policy
    rightsizer.io/example: "true"
spec:
  enabled: {{ .enabled }}
  priority: {{ .priority }}
  mode: {{ .mode }}
  {{- if .dryRun }}
  dryRun: {{ .dryRun }}
  {{- end }}

  targetRef:
    kind: {{ .targetRef.kind }}
    {{- if .targetRef.apiVersion }}
    apiVersion: {{ .targetRef.apiVersion }}
    {{- end }}
    {{- if .targetRef.namespaces }}
    namespaces:
      {{- range .targetRef.namespaces }}
      - {{ . }}
      {{- end }}
    {{- end }}
    {{- if .targetRef.excludeNamespaces }}
    excludeNamespaces:
      {{- range .targetRef.excludeNamespaces }}
      - {{ . }}
      {{- end }}
    {{- end }}
    {{- if .targetRef.labelSelector }}
    labelSelector:
      {{- if .targetRef.labelSelector.matchLabels }}
      matchLabels:
        {{- range $key, $value := .targetRef.labelSelector.matchLabels }}
        {{ $key }}: {{ $value }}
        {{- end }}
      {{- end }}
      {{- if .targetRef.labelSelector.matchExpressions }}
      matchExpressions:
        {{- range .targetRef.labelSelector.matchExpressions }}
        - key: {{ .key }}
          operator: {{ .operator }}
          {{- if .values }}
          values:
            {{- range .values }}
            - {{ . }}
            {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
    {{- if .targetRef.annotationSelector }}
    annotationSelector:
      {{- range $key, $value := .targetRef.annotationSelector }}
      {{ $key }}: {{ $value }}
      {{- end }}
    {{- end }}
    {{- if .targetRef.names }}
    names:
      {{- range .targetRef.names }}
      - {{ . }}
      {{- end }}
    {{- end }}
    {{- if .targetRef.excludeNames }}
    excludeNames:
      {{- range .targetRef.excludeNames }}
      - {{ . }}
      {{- end }}
    {{- end }}

  {{- if .resourceStrategy }}
  resourceStrategy:
    {{- if .resourceStrategy.cpu }}
    cpu:
      {{- if .resourceStrategy.cpu.requestMultiplier }}
      requestMultiplier: {{ .resourceStrategy.cpu.requestMultiplier }}
      {{- end }}
      {{- if .resourceStrategy.cpu.requestAddition }}
      requestAddition: {{ .resourceStrategy.cpu.requestAddition }}
      {{- end }}
      {{- if .resourceStrategy.cpu.limitMultiplier }}
      limitMultiplier: {{ .resourceStrategy.cpu.limitMultiplier }}
      {{- end }}
      {{- if .resourceStrategy.cpu.limitAddition }}
      limitAddition: {{ .resourceStrategy.cpu.limitAddition }}
      {{- end }}
      {{- if .resourceStrategy.cpu.minRequest }}
      minRequest: {{ .resourceStrategy.cpu.minRequest }}
      {{- end }}
      {{- if .resourceStrategy.cpu.maxLimit }}
      maxLimit: {{ .resourceStrategy.cpu.maxLimit }}
      {{- end }}
      {{- if .resourceStrategy.cpu.targetUtilization }}
      targetUtilization: {{ .resourceStrategy.cpu.targetUtilization }}
      {{- end }}
    {{- end }}
    {{- if .resourceStrategy.memory }}
    memory:
      {{- if .resourceStrategy.memory.requestMultiplier }}
      requestMultiplier: {{ .resourceStrategy.memory.requestMultiplier }}
      {{- end }}
      {{- if .resourceStrategy.memory.requestAddition }}
      requestAddition: {{ .resourceStrategy.memory.requestAddition }}
      {{- end }}
      {{- if .resourceStrategy.memory.limitMultiplier }}
      limitMultiplier: {{ .resourceStrategy.memory.limitMultiplier }}
      {{- end }}
      {{- if .resourceStrategy.memory.limitAddition }}
      limitAddition: {{ .resourceStrategy.memory.limitAddition }}
      {{- end }}
      {{- if .resourceStrategy.memory.minRequest }}
      minRequest: {{ .resourceStrategy.memory.minRequest }}
      {{- end }}
      {{- if .resourceStrategy.memory.maxLimit }}
      maxLimit: {{ .resourceStrategy.memory.maxLimit }}
      {{- end }}
      {{- if .resourceStrategy.memory.targetUtilization }}
      targetUtilization: {{ .resourceStrategy.memory.targetUtilization }}
      {{- end }}
    {{- end }}
    {{- if .resourceStrategy.metricsSource }}
    metricsSource: {{ .resourceStrategy.metricsSource }}
    {{- end }}
    {{- if .resourceStrategy.prometheusConfig }}
    prometheusConfig:
      url: {{ .resourceStrategy.prometheusConfig.url }}
      {{- if .resourceStrategy.prometheusConfig.cpuQuery }}
      cpuQuery: {{ .resourceStrategy.prometheusConfig.cpuQuery }}
      {{- end }}
      {{- if .resourceStrategy.prometheusConfig.memoryQuery }}
      memoryQuery: {{ .resourceStrategy.prometheusConfig.memoryQuery }}
      {{- end }}
    {{- end }}
    {{- if .resourceStrategy.historyWindow }}
    historyWindow: {{ .resourceStrategy.historyWindow }}
    {{- end }}
    {{- if .resourceStrategy.percentile }}
    percentile: {{ .resourceStrategy.percentile }}
    {{- end }}
    {{- if .resourceStrategy.updateMode }}
    updateMode: {{ .resourceStrategy.updateMode }}
    {{- end }}
  {{- end }}

  {{- if .schedule }}
  schedule:
    {{- if .schedule.interval }}
    interval: {{ .schedule.interval }}
    {{- end }}
    {{- if .schedule.cronSchedule }}
    cronSchedule: {{ .schedule.cronSchedule }}
    {{- end }}
    {{- if .schedule.timeWindows }}
    timeWindows:
      {{- range .schedule.timeWindows }}
      - start: {{ .start }}
        end: {{ .end }}
        {{- if .daysOfWeek }}
        daysOfWeek:
          {{- range .daysOfWeek }}
          - {{ . }}
          {{- end }}
        {{- end }}
        {{- if .timezone }}
        timezone: {{ .timezone }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}

  {{- if .constraints }}
  constraints:
    {{- if .constraints.maxChangePercentage }}
    maxChangePercentage: {{ .constraints.maxChangePercentage }}
    {{- end }}
    {{- if .constraints.minChangeThreshold }}
    minChangeThreshold: {{ .constraints.minChangeThreshold }}
    {{- end }}
    {{- if .constraints.cooldownPeriod }}
    cooldownPeriod: {{ .constraints.cooldownPeriod }}
    {{- end }}
    {{- if .constraints.maxRestartsPerHour }}
    maxRestartsPerHour: {{ .constraints.maxRestartsPerHour }}
    {{- end }}
    {{- if .constraints.respectPDB }}
    respectPDB: {{ .constraints.respectPDB }}
    {{- end }}
    {{- if .constraints.respectHPA }}
    respectHPA: {{ .constraints.respectHPA }}
    {{- end }}
    {{- if .constraints.respectVPA }}
    respectVPA: {{ .constraints.respectVPA }}
    {{- end }}
  {{- end }}

  {{- if .webhooks }}
  webhooks:
    {{- range .webhooks }}
    - url: {{ .url }}
      {{- if .events }}
      events:
        {{- range .events }}
        - {{ . }}
        {{- end }}
      {{- end }}
      {{- if .headers }}
      headers:
        {{- range $key, $value := .headers }}
        {{ $key }}: {{ $value }}
        {{- end }}
      {{- end }}
      {{- if .retryPolicy }}
      retryPolicy:
        maxRetries: {{ .retryPolicy.maxRetries }}
        retryInterval: {{ .retryPolicy.retryInterval }}
      {{- end }}
    {{- end }}
  {{- end }}

  {{- if .resourceAnnotations }}
  resourceAnnotations:
    {{- range $key, $value := .resourceAnnotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
