apiVersion: v1
kind: Pod
metadata:
  name: test-skip-logic
  namespace: default
spec:
  containers:
  - name: app
    image: nginx:alpine
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "200m"
        memory: "512Mi"
