apiVersion: v1
kind: Namespace
metadata:
  name: test-workloads
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
  namespace: test-workloads
  labels:
    app: nginx-demo
    managed-by: right-sizer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-test
  namespace: test-workloads
  labels:
    app: stress-test
    managed-by: right-sizer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stress-test
  template:
    metadata:
      labels:
        app: stress-test
    spec:
      containers:
      - name: stress
        image: progrium/stress
        args:
        - "--cpu"
        - "1"
        - "--io"
        - "1"
        - "--vm"
        - "1"
        - "--vm-bytes"
        - "128M"
        - "--timeout"
        - "600s"
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cache
  namespace: test-workloads
  labels:
    app: redis-cache
    managed-by: right-sizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-cache
  template:
    metadata:
      labels:
        app: redis-cache
    spec:
      containers:
      - name: redis
        image: redis:alpine
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 6379
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: test-workloads
spec:
  selector:
    app: nginx-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: test-workloads
spec:
  selector:
    app: redis-cache
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  type: ClusterIP
