apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "right-sizer.fullname" . }}
  labels:
    {{- include "right-sizer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "right-sizer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "right-sizer.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "right-sizer.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: health
              containerPort: 8081
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.metricsPort | default 9090 }}
              protocol: TCP
            - name: api
              containerPort: 8082
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          startupProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 30
            successThreshold: 1
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LOG_LEVEL
              value: {{ .Values.rightsizerConfig.logging.level | default "info" | quote }}
            - name: LOG_FORMAT
              value: {{ .Values.rightsizerConfig.logging.format | default "json" | quote }}
            - name: METRICS_PORT
              value: {{ .Values.metricsPort | default 9090 | quote }}
            - name: ENABLE_LEADER_ELECTION
              value: {{ .Values.rightsizerConfig.operator.leaderElection | default true | quote }}
            - name: LEADER_ELECTION_NAMESPACE
              value: {{ .Values.rightsizerConfig.operator.leaderElectionNamespace | default .Release.Namespace | quote }}
            - name: LEADER_ELECTION_ID
              value: {{ .Values.rightsizerConfig.operator.leaderElectionID | default "right-sizer-leader" | quote }}
            # AIOPS / CAPABILITY CONFIGURATION
            - name: AIOPS_ENABLED
              value: {{ .Values.aiops.enabled | default true | quote }}
            - name: AIOPS_ENGINE_DISPATCH_INTERVAL
              value: {{ .Values.aiops.engine.dispatchInterval | default "5s" | quote }}
            # Memory leak analyzer
            - name: AIOPS_MEMORY_LEAK_ANALYZER
              value: {{ .Values.aiops.analyzers.memoryLeak.enabled | default true | quote }}
            - name: AIOPS_MEMORY_LEAK_MIN_RSS
              value: {{ .Values.aiops.analyzers.memoryLeak.minRSSThreshold | default "64MiB" | quote }}
            - name: AIOPS_MEMORY_LEAK_R2_THRESHOLD
              value: {{ .Values.aiops.analyzers.memoryLeak.r2Threshold | default 0.55 | quote }}
            - name: AIOPS_MEMORY_LEAK_MIN_SLOPE_MB_PER_MIN
              value: {{ .Values.aiops.analyzers.memoryLeak.minSlopeMBPerMinute | default 0.2 | quote }}
            # Incident store
            - name: AIOPS_INCIDENT_RETENTION
              value: {{ .Values.aiops.incidentStore.retention | default "24h" | quote }}
            - name: AIOPS_INCIDENT_MAX
              value: {{ .Values.aiops.incidentStore.maxIncidents | default 500 | quote }}
            # Capability policy
            - name: CAPABILITIES_MIN_MINOR
              value: {{ .Values.capabilities.enforceMinimumMinor | default 33 | quote }}
            - name: CAPABILITIES_FAIL_UNSUPPORTED
              value: {{ .Values.capabilities.failOnUnsupported | default false | quote }}
            # Narrative / LLM
            - name: LLM_ENABLED
              value: {{ ternary "true" "false" (.Values.aiops.narrative.llm.enabled) | quote }}
            - name: LLM_MODEL
              value: {{ .Values.aiops.narrative.llm.model | default "" | quote }}
            - name: LLM_API_URL
              value: {{ .Values.aiops.narrative.llm.apiURL | default "" | quote }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ include "right-sizer.fullname" . }}-config
            optional: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
