{{- if .Values.rightsizerConfig.create }}
apiVersion: rightsizer.io/v1alpha1
kind: RightSizerConfig
metadata:
  name: {{ include "right-sizer.fullname" . }}-config
  labels:
    {{- include "right-sizer.labels" . | nindent 4 }}
spec:
  # Core configuration
  enabled: {{ .Values.rightsizerConfig.enabled | default true }}
  defaultMode: {{ .Values.rightsizerConfig.mode | default "balanced" | quote }}
  resizeInterval: {{ .Values.rightsizerConfig.operationalConfig.resizeInterval | default "5m" | quote }}
  dryRun: {{ .Values.rightsizerConfig.dryRun | default false }}

  # Default resource sizing strategy
  defaultResourceStrategy:
    cpu:
      requestMultiplier: 1.2
      requestAddition: 0
      limitMultiplier: 2.0
      limitAddition: 0
      minRequest: "10m"
      maxLimit: "4000m"
      scaleUpThreshold: 0.8
      scaleDownThreshold: 0.3
    memory:
      requestMultiplier: 1.2
      requestAddition: 0
      limitMultiplier: 2.0
      limitAddition: 0
      minRequest: "64Mi"
      maxLimit: "8192Mi"
      scaleUpThreshold: 0.8
      scaleDownThreshold: 0.3
    historyWindow: "7d"
    algorithm: "percentile"
    percentile: 95

  # Global constraints for resource changes
  globalConstraints:
    maxChangePercentage: 50
    minChangeThreshold: 10
    maxMemoryGB: 32
    maxCPUCores: 16
    preventOOMKill: true
    respectPodDisruptionBudget: true

  # Metrics configuration
  metricsConfig:
    provider: {{ .Values.rightsizerConfig.monitoring.metricsProvider | default "metrics-server" | quote }}
    {{- with .Values.rightsizerConfig.monitoring }}
    {{- if .prometheusURL }}
    prometheusEndpoint: {{ .prometheusURL | quote }}
    {{- end }}
    {{- if .metricsServerEndpoint }}
    metricsServerEndpoint: {{ .metricsServerEndpoint | quote }}
    {{- end }}
    {{- end }}
    scrapeInterval: "30s"
    historyRetention: "30d"
    aggregationMethod: "avg"
    includeCustomMetrics: false

  # Observability configuration
  observabilityConfig:
    logLevel: {{ .Values.rightsizerConfig.logging.level | default "info" | quote }}
    logFormat: {{ .Values.rightsizerConfig.logging.format | default "json" | quote }}
    enableAuditLogging: {{ .Values.rightsizerConfig.logging.enableAudit | default true }}
    enableMetricsExport: true
    metricsPort: 9090
    enableTracing: false
    {{- with .Values.rightsizerConfig.observability }}
    {{- if .tracingEndpoint }}
    tracingEndpoint: {{ .tracingEndpoint | quote }}
    {{- end }}
    {{- end }}
    enableProfiling: false
    profilingPort: 6060

  # Security configuration
  securityConfig:
    enableAdmissionController: false
    admissionWebhookPort: 8443
    requireAnnotation: false
    annotationKey: "rightsizer.io/enable"
    enableMutatingWebhook: false
    enableValidatingWebhook: false
    tlsCertDir: "/tmp/certs"
    webhookTimeoutSeconds: 10

  # Operator configuration
  operatorConfig:
    leaderElection: true
    leaderElectionNamespace: {{ .Release.Namespace | quote }}
    leaderElectionID: "right-sizer-leader"
    leaderElectionLeaseDuration: "15s"
    leaderElectionRenewDeadline: "10s"
    leaderElectionRetryPeriod: "2s"
    syncPeriod: "30s"
    maxConcurrentReconciles: 3
    workerThreads: 10
    qps: 20
    burst: 30
    retryAttempts: 3
    retryInterval: "5s"
    healthProbePort: 8081
    readinessEndpoint: "/readyz"
    livenessEndpoint: "/healthz"

  # Namespace configuration
  namespaceConfig:
    {{- with .Values.rightsizerConfig.namespaceConfig }}
    {{- if .includeNamespaces }}
    includeNamespaces:
    {{- range .includeNamespaces }}
      - {{ . | quote }}
    {{- end }}
    {{- else }}
    includeNamespaces: []
    {{- end }}
    {{- if .excludeNamespaces }}
    excludeNamespaces:
    {{- range .excludeNamespaces }}
      - {{ . | quote }}
    {{- end }}
    {{- else }}
    excludeNamespaces:
      - "kube-system"
      - "kube-public"
      - "kube-node-lease"
      - "cert-manager"
      - "ingress-nginx"
      - "istio-system"
      - {{ $.Release.Namespace | quote }}
    {{- end }}
    {{- if .systemNamespaces }}
    systemNamespaces:
    {{- range .systemNamespaces }}
      - {{ . | quote }}
    {{- end }}
    {{- else }}
    systemNamespaces:
      - "kube-system"
      - "kube-public"
      - "kube-node-lease"
      - "cert-manager"
      - "ingress-nginx"
      - "istio-system"
    {{- end }}
    {{- if .namespaceLabels }}
    namespaceLabels:
      {{- toYaml .namespaceLabels | nindent 6 }}
    {{- end }}
    {{- else }}
    includeNamespaces: []
    excludeNamespaces:
      - "kube-system"
      - "kube-public"
      - "kube-node-lease"
      - "cert-manager"
      - "ingress-nginx"
      - "istio-system"
      - {{ $.Release.Namespace | quote }}
    systemNamespaces:
      - "kube-system"
      - "kube-public"
      - "kube-node-lease"
      - "cert-manager"
      - "ingress-nginx"
      - "istio-system"
    {{- end }}

  # Notification configuration
  notificationConfig:
    {{- with .Values.rightsizerConfig.notifications }}
    {{- if .enabled }}
    enableNotifications: true
    {{- with .slack }}
    slackConfig:
      webhookURL: {{ .webhookURL | quote }}
      channel: {{ .channel | default "#right-sizer" | quote }}
      username: {{ .username | default "RightSizer" | quote }}
      iconEmoji: {{ .iconEmoji | default ":robot:" | quote }}
      notifyOnSuccess: {{ .notifyOnSuccess | default false }}
      notifyOnFailure: {{ .notifyOnFailure | default true }}
      notifyOnDryRun: {{ .notifyOnDryRun | default false }}
    {{- end }}
    {{- with .email }}
    emailConfig:
      smtpHost: {{ .smtpHost | quote }}
      smtpPort: {{ .smtpPort | default 587 }}
      smtpUsername: {{ .smtpUsername | quote }}
      smtpPasswordSecret: {{ .smtpPasswordSecret | quote }}
      from: {{ .from | quote }}
      to:
      {{- range .to }}
        - {{ . | quote }}
      {{- end }}
      subject: {{ .subject | default "RightSizer Alert" | quote }}
    {{- end }}
    {{- with .webhook }}
    webhookConfig:
      - url: {{ .url | quote }}
        method: {{ .method | default "POST" | quote }}
        {{- if .headers }}
        headers:
          {{- toYaml .headers | nindent 10 }}
        {{- end }}
        retryCount: {{ .retryCount | default 3 }}
        retryDelay: {{ .retryDelay | default "5s" | quote }}
    {{- end }}
    {{- else }}
    enableNotifications: false
    {{- end }}
    {{- else }}
    enableNotifications: false
    {{- end }}

  # Feature gates for experimental features
  featureGates:
    EnableInPlaceResize: true
    EnablePredictiveScaling: false
    EnableCostOptimization: false
    EnableMultiCluster: false
    EnableAutoLearning: false
    EnableWorkloadProfiling: false
    EnableAdvancedScheduling: false
{{- end }}
