{{- if .Values.rightsizerConfig.create }}
apiVersion: rightsizer.io/v1alpha1
kind: RightSizerConfig
metadata:
  name: {{ include "right-sizer.fullname" . }}-config
  labels:
    {{- include "right-sizer.labels" . | nindent 4 }}
spec:
  # Core configuration
  enabled: {{ .Values.rightsizerConfig.enabled | default true }}
  defaultMode: {{ .Values.rightsizerConfig.mode | default "balanced" | quote }}
  resizeInterval: {{ .Values.rightsizerConfig.operationalConfig.resizeInterval | default "5m" | quote }}
  dryRun: {{ .Values.rightsizerConfig.dryRun | default false }}

  # Default resource sizing strategy
  defaultResourceStrategy:
    cpu:
      requestMultiplier: 1.2
      requestAddition: 0
      limitMultiplier: 2.0
      limitAddition: 0
      minRequest: "10m"
      maxLimit: "4000m"
      scaleUpThreshold: 0.8
      scaleDownThreshold: 0.3
    memory:
      requestMultiplier: 1.2
      requestAddition: 0
      limitMultiplier: 2.0
      limitAddition: 0
      minRequest: "64Mi"
      maxLimit: "8192Mi"
      scaleUpThreshold: 0.8
      scaleDownThreshold: 0.3
    historyWindow: "7d"
    algorithm: "percentile"
    percentile: 95

  # Global constraints for resource changes
  globalConstraints:
    maxChangePercentage: {{ .Values.rightsizerConfig.constraints.maxChangePercentage | default 50 }}
    minChangeThreshold: {{ .Values.rightsizerConfig.constraints.minChangeThreshold | default 5 }}
    maxMemoryGB: {{ .Values.rightsizerConfig.constraints.maxMemoryGB | default 32 }}
    maxCPUCores: {{ .Values.rightsizerConfig.constraints.maxCPUCores | default 16 }}
    cooldownPeriod: {{ .Values.rightsizerConfig.constraints.cooldownPeriod | default "5m" | quote }}
    maxConcurrentResizes: {{ .Values.rightsizerConfig.constraints.maxConcurrentResizes | default 10 }}
    respectPDB: {{ .Values.rightsizerConfig.constraints.respectPDB | default true }}
    respectHPA: {{ .Values.rightsizerConfig.constraints.respectHPA | default true }}
    respectVPA: {{ .Values.rightsizerConfig.constraints.respectVPA | default true }}

  # Metrics configuration
  metricsConfig:
    provider: {{ .Values.rightsizerConfig.monitoring.metricsProvider | default "metrics-server" | quote }}
    {{- with .Values.rightsizerConfig.monitoring }}
    {{- if .prometheusURL }}
    prometheusEndpoint: {{ .prometheusURL | quote }}
    {{- end }}
    {{- if .metricsServerEndpoint }}
    metricsServerEndpoint: {{ .metricsServerEndpoint | quote }}
    {{- end }}
    {{- end }}
    scrapeInterval: "30s"
    historyRetention: "30d"
    aggregationMethod: "avg"
    includeCustomMetrics: false

  # Observability configuration
  observabilityConfig:
    logLevel: {{ .Values.rightsizerConfig.logging.level | default "info" | quote }}
    logFormat: {{ .Values.rightsizerConfig.logging.format | default "json" | quote }}
    enableAuditLog: {{ .Values.rightsizerConfig.logging.enableAudit | default true }}
    enableEvents: {{ .Values.rightsizerConfig.logging.enableEvents | default true }}
    enableMetricsExport: true
    metricsPort: 9090
    enableTracing: false
    enableProfiling: false
    profilingPort: 6060
    auditLogPath: "/var/log/right-sizer/audit.log"
    {{- with .Values.rightsizerConfig.observability }}
    {{- if .tracingEndpoint }}
    tracingEndpoint: {{ .tracingEndpoint | quote }}
    {{- end }}
    {{- end }}

  # Security configuration
  securityConfig:
    enableAdmissionController: false
    admissionWebhookPort: 8443
    requireAnnotation: false
    annotationKey: "rightsizer.io/enable"
    enableMutatingWebhook: false
    enableValidatingWebhook: false
    tlsCertDir: "/tmp/certs"
    webhookTimeoutSeconds: 10

  # Operator configuration
  operatorConfig:
    leaderElection: true
    leaderElectionNamespace: {{ .Release.Namespace | quote }}
    leaderElectionID: "right-sizer-leader"
    leaderElectionLeaseDuration: "15s"
    leaderElectionRenewDeadline: "10s"
    leaderElectionRetryPeriod: "2s"
    syncPeriod: "30s"
    maxConcurrentReconciles: 3
    workerThreads: 10
    qps: 20
    burst: 30
    retryAttempts: 3
    retryInterval: "5s"
    healthProbePort: 8081
    readinessEndpoint: "/readyz"
    livenessEndpoint: "/healthz"
    enableCircuitBreaker: true
    circuitBreakerThreshold: 5
    reconcileInterval: "10m"
    maxRetries: 3

  # Namespace configuration
  namespaceConfig:
    {{- with .Values.rightsizerConfig.namespaceConfig }}
    {{- if .includeNamespaces }}
    includeNamespaces:
    {{- range .includeNamespaces }}
      - {{ . | quote }}
    {{- end }}
    {{- else }}
    includeNamespaces: []
    {{- end }}
    {{- if .excludeNamespaces }}
    excludeNamespaces:
    {{- range .excludeNamespaces }}
      - {{ . | quote }}
    {{- end }}
    {{- else }}
    excludeNamespaces:
      - "kube-system"
      - "kube-public"
      - "kube-node-lease"
      - "cert-manager"
      - "ingress-nginx"
      - "istio-system"
      - {{ $.Release.Namespace | quote }}
    {{- end }}
    {{- if .systemNamespaces }}
    systemNamespaces:
    {{- range .systemNamespaces }}
      - {{ . | quote }}
    {{- end }}
    {{- else }}
    systemNamespaces:
      - "kube-system"
      - "kube-public"
      - "kube-node-lease"
      - "cert-manager"
      - "ingress-nginx"
      - "istio-system"
    {{- end }}
    {{- if .namespaceLabels }}
    namespaceLabels:
      {{- toYaml .namespaceLabels | nindent 6 }}
    {{- end }}
    {{- else }}
    includeNamespaces: []
    excludeNamespaces:
      - "kube-system"
      - "kube-public"
      - "kube-node-lease"
      - "cert-manager"
      - "ingress-nginx"
      - "istio-system"
      - {{ $.Release.Namespace | quote }}
    systemNamespaces:
      - "kube-system"
      - "kube-public"
      - "kube-node-lease"
      - "cert-manager"
      - "ingress-nginx"
      - "istio-system"
    {{- end }}

  # Notification configuration
  notificationConfig:
    {{- with .Values.rightsizerConfig.notifications }}
    {{- if .enabled }}
    enableNotifications: true
    {{- with .slack }}
    slackConfig:
      webhookURL: {{ .webhookURL | quote }}
      {{- if .channel }}
      channel: {{ .channel | quote }}
      {{- end }}
      {{- if .username }}
      username: {{ .username | quote }}
      {{- end }}
      {{- if .iconEmoji }}
      iconEmoji: {{ .iconEmoji | quote }}
      {{- end }}
    {{- end }}
    {{- with .email }}
    emailConfig:
      smtpServer: {{ .smtpServer | quote }}
      smtpPort: {{ .smtpPort | default 587 }}
      {{- if .authSecretRef }}
      authSecretRef:
        name: {{ .authSecretRef.name | quote }}
        key: {{ .authSecretRef.key | default "password" | quote }}
        {{- if .authSecretRef.optional }}
        optional: {{ .authSecretRef.optional }}
        {{- end }}
      {{- end }}
      from: {{ .from | quote }}
      to:
      {{- range .to }}
        - {{ . | quote }}
      {{- end }}
      useTLS: {{ .useTLS | default true }}
    {{- end }}
    {{- with .webhook }}
    webhookConfigs:
      - name: {{ .name | default "default-webhook" | quote }}
        url: {{ .url | quote }}
        {{- if .method }}
        method: {{ .method | quote }}
        {{- end }}
        {{- if .headers }}
        headers:
          {{- toYaml .headers | nindent 10 }}
        {{- end }}
        {{- if .retryCount }}
        retryCount: {{ .retryCount }}
        {{- end }}
        {{- if .timeout }}
        timeout: {{ .timeout | quote }}
        {{- end }}
    {{- end }}
    notificationLevel: {{ .notificationLevel | default "warning" | quote }}
    {{- else }}
    enableNotifications: false
    notificationLevel: "warning"
    {{- end }}
    {{- else }}
    enableNotifications: false
    notificationLevel: "warning"
    {{- end }}

  # Feature gates for experimental features
  featureGates:
    UpdateResizePolicy: {{ .Values.rightsizerConfig.featureGates.updateResizePolicy | default false }}
    EnablePredictiveScaling: {{ .Values.rightsizerConfig.featureGates.enablePredictiveScaling | default false }}
    EnableCostOptimization: {{ .Values.rightsizerConfig.featureGates.enableCostOptimization | default false }}
    EnableMultiCluster: {{ .Values.rightsizerConfig.featureGates.enableMultiCluster | default false }}
    EnableAutoLearning: {{ .Values.rightsizerConfig.featureGates.enableAutoLearning | default false }}
    EnableWorkloadProfiling: {{ .Values.rightsizerConfig.featureGates.enableWorkloadProfiling | default false }}
    EnableAdvancedScheduling: {{ .Values.rightsizerConfig.featureGates.enableAdvancedScheduling | default false }}
{{- end }}
