{{- if .Values.rightsizerConfig.create }}
apiVersion: rightsizer.io/v1alpha1
kind: RightSizerConfig
metadata:
  name: {{ include "right-sizer.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "right-sizer.labels" . | nindent 4 }}
spec:
  # Enable or disable the right-sizer operator
  enabled: {{ .Values.rightsizerConfig.enabled | default true }}

  # Operating mode: balanced, aggressive, conservative
  defaultMode: {{ .Values.rightsizerConfig.mode | default "balanced" | quote }}

  # How often to check and resize resources
  resizeInterval: {{ .Values.rightsizerConfig.operationalConfig.resizeInterval | default "30s" | quote }}

  # Dry-run mode - only logs recommendations without applying changes
  dryRun: {{ .Values.rightsizerConfig.dryRun | default false }}
{{- end }}
