{{- if .Values.rightsizerConfig.create }}
apiVersion: rightsizer.io/v1alpha1
kind: RightSizerConfig
metadata:
  name: {{ include "right-sizer.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "right-sizer.labels" . | nindent 4 }}
spec:
  # Enable or disable the right-sizer operator
  enabled: {{ .Values.rightsizerConfig.enabled | default true }}

  # Operating mode: adaptive, aggressive, conservative, or custom
  mode: {{ .Values.rightsizerConfig.mode | default "adaptive" }}

  # Dry-run mode - only logs recommendations without applying changes
  dryRun: {{ .Values.rightsizerConfig.dryRun | default false }}

  # Resource defaults and limits
  resourceDefaults:
    cpu:
      defaultRequest: {{ .Values.rightsizerConfig.resourceDefaults.cpu.defaultRequest | default "100m" | quote }}
      defaultLimit: {{ .Values.rightsizerConfig.resourceDefaults.cpu.defaultLimit | default "2000m" | quote }}
      requestToLimitRatio: {{ .Values.rightsizerConfig.resourceDefaults.cpu.requestToLimitRatio | default 2.0 }}
      minRequest: {{ .Values.rightsizerConfig.resourceDefaults.cpu.minRequest | default "10m" | quote }}
      maxLimit: {{ .Values.rightsizerConfig.resourceDefaults.cpu.maxLimit | default "4000m" | quote }}
    memory:
      defaultRequest: {{ .Values.rightsizerConfig.resourceDefaults.memory.defaultRequest | default "128Mi" | quote }}
      defaultLimit: {{ .Values.rightsizerConfig.resourceDefaults.memory.defaultLimit | default "2Gi" | quote }}
      requestToLimitRatio: {{ .Values.rightsizerConfig.resourceDefaults.memory.requestToLimitRatio | default 1.5 }}
      minRequest: {{ .Values.rightsizerConfig.resourceDefaults.memory.minRequest | default "64Mi" | quote }}
      maxLimit: {{ .Values.rightsizerConfig.resourceDefaults.memory.maxLimit | default "8Gi" | quote }}

  # Sizing strategy configuration
  sizingStrategy:
    # Algorithm: percentile, peak, average
    algorithm: {{ .Values.rightsizerConfig.sizingStrategy.algorithm | default "percentile" | quote }}

    # Historical data analysis period
    lookbackPeriod: {{ .Values.rightsizerConfig.sizingStrategy.lookbackPeriod | default "7d" | quote }}

    # Metrics sampling interval
    sampleInterval: {{ .Values.rightsizerConfig.sizingStrategy.sampleInterval | default "1m" | quote }}

    # Percentile to use (if algorithm is percentile)
    percentile: {{ .Values.rightsizerConfig.sizingStrategy.percentile | default 95 }}

    # Scaling factors
    scalingFactors:
      # Multiplier for scaling up resources
      scaleUpMultiplier: {{ .Values.rightsizerConfig.sizingStrategy.scalingFactors.scaleUpMultiplier | default 1.2 }}
      # Multiplier for scaling down resources
      scaleDownMultiplier: {{ .Values.rightsizerConfig.sizingStrategy.scalingFactors.scaleDownMultiplier | default 0.9 }}
      # Minimum percentage change required to trigger resize
      minChangeThreshold: {{ .Values.rightsizerConfig.sizingStrategy.scalingFactors.minChangeThreshold | default 10 }}

    # Buffer/burst capacity configuration
    burstCapacity:
      # Additional CPU capacity for bursts (percentage)
      cpuBurstPercentage: {{ .Values.rightsizerConfig.sizingStrategy.burstCapacity.cpuBurstPercentage | default 30 }}
      # Additional memory capacity for bursts (percentage)
      memoryBurstPercentage: {{ .Values.rightsizerConfig.sizingStrategy.burstCapacity.memoryBurstPercentage | default 20 }}

  # Monitoring configuration
  monitoring:
    # Metrics provider: metrics-server, prometheus
    metricsProvider: {{ .Values.rightsizerConfig.monitoring.metricsProvider | default "metrics-server" | quote }}
    {{- if .Values.rightsizerConfig.monitoring.prometheusURL }}
    prometheusURL: {{ .Values.rightsizerConfig.monitoring.prometheusURL | quote }}
    {{- end }}
    scrapeInterval: {{ .Values.rightsizerConfig.monitoring.scrapeInterval | default "30s" | quote }}
    retentionPeriod: {{ .Values.rightsizerConfig.monitoring.retentionPeriod | default "30d" | quote }}

  # Operational configuration
  operationalConfig:
    # Resize mode: InPlace (for k8s 1.27+) or Rolling
    resizeMode: {{ .Values.rightsizerConfig.operationalConfig.resizeMode | default "InPlace" | quote }}

    # How often to check and resize resources
    resizeInterval: {{ .Values.rightsizerConfig.operationalConfig.resizeInterval | default "5m" | quote }}

    # Number of workloads to process in a batch
    batchSize: {{ .Values.rightsizerConfig.operationalConfig.batchSize | default 10 }}

    # Number of concurrent resize operations
    concurrentOperations: {{ .Values.rightsizerConfig.operationalConfig.concurrentOperations | default 5 }}

    # Retry configuration
    retryAttempts: {{ .Values.rightsizerConfig.operationalConfig.retryAttempts | default 3 }}
    retryBackoff: {{ .Values.rightsizerConfig.operationalConfig.retryBackoff | default "exponential" | quote }}

    {{- if .Values.rightsizerConfig.operationalConfig.maintenanceWindow.enabled }}
    # Maintenance window configuration
    maintenanceWindow:
      enabled: true
      schedule: {{ .Values.rightsizerConfig.operationalConfig.maintenanceWindow.schedule | default "0 2 * * *" | quote }}
      duration: {{ .Values.rightsizerConfig.operationalConfig.maintenanceWindow.duration | default "2h" | quote }}
      timezone: {{ .Values.rightsizerConfig.operationalConfig.maintenanceWindow.timezone | default "UTC" | quote }}
    {{- end }}

  # Namespace configuration
  namespaceConfig:
    {{- if .Values.rightsizerConfig.namespaceConfig.includeNamespaces }}
    # Namespaces to include for right-sizing
    includeNamespaces:
    {{- range .Values.rightsizerConfig.namespaceConfig.includeNamespaces }}
      - {{ . | quote }}
    {{- end }}
    {{- else }}
    # Include all namespaces by default (except excluded ones)
    includeNamespaces: []
    {{- end }}

    # Namespaces to exclude from right-sizing
    excludeNamespaces:
    {{- if .Values.rightsizerConfig.namespaceConfig.excludeNamespaces }}
    {{- range .Values.rightsizerConfig.namespaceConfig.excludeNamespaces }}
      - {{ . | quote }}
    {{- end }}
    {{- else }}
      - kube-system
      - kube-public
      - kube-node-lease
      - {{ .Release.Namespace }}
    {{- end }}

    # System namespaces that should never be modified
    systemNamespaces:
      - kube-system
      - kube-public
      - kube-node-lease
      - cert-manager
      - ingress-nginx
      - istio-system
      - linkerd
      - {{ .Release.Namespace }}

  # Logging configuration
  logging:
    level: {{ .Values.rightsizerConfig.logging.level | default "info" | quote }}
    format: {{ .Values.rightsizerConfig.logging.format | default "json" | quote }}
    enableAudit: {{ .Values.rightsizerConfig.logging.enableAudit | default true }}
    {{- if .Values.rightsizerConfig.logging.auditLogPath }}
    auditLogPath: {{ .Values.rightsizerConfig.logging.auditLogPath | quote }}
    {{- end }}

  {{- if .Values.rightsizerConfig.notifications.enabled }}
  # Notification configuration
  notifications:
    enabled: true
    channels:
    {{- range .Values.rightsizerConfig.notifications.channels }}
      - type: {{ .type | quote }}
        {{- if .webhook }}
        webhook: {{ .webhook | quote }}
        {{- end }}
        {{- if .email }}
        email: {{ .email | quote }}
        {{- end }}
        {{- if .slack }}
        slack:
          webhook: {{ .slack.webhook | quote }}
          channel: {{ .slack.channel | quote }}
        {{- end }}
    {{- end }}
  {{- end }}

  {{- if .Values.rightsizerConfig.annotations }}
  # Custom annotations for workloads
  annotations:
    {{- range $key, $value := .Values.rightsizerConfig.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}

  {{- if .Values.rightsizerConfig.labels }}
  # Custom labels for workloads
  labels:
    {{- range $key, $value := .Values.rightsizerConfig.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
{{- end }}
