{{- if .Values.dashboard.apiToken.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "right-sizer.fullname" . }}-dashboard
  labels:
    {{- include "right-sizer.labels" . | nindent 4 }}
    app.kubernetes.io/component: dashboard-credentials
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    {{- with .Values.dashboard.apiToken.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
{{- if .Values.dashboard.apiToken.value }}
stringData:
  api-token: {{ .Values.dashboard.apiToken.value | quote }}
{{- else if .Values.dashboard.apiToken.generateRandom }}
data:
  api-token: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
---
{{- end }}
{{- if .Values.dashboard.cluster.secretCreate }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "right-sizer.fullname" . }}-cluster
  labels:
    {{- include "right-sizer.labels" . | nindent 4 }}
    app.kubernetes.io/component: cluster-credentials
  annotations:
    {{- with .Values.dashboard.cluster.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  cluster-id: {{ .Values.dashboard.cluster.id | default (include "right-sizer.fullname" .) | b64enc | quote }}
  cluster-name: {{ .Values.dashboard.cluster.name | default .Values.global.clusterName | default "default" | b64enc | quote }}
---
{{- end }}
{{- if .Values.aiops }}
{{- if .Values.aiops.enabled }}
{{- if .Values.aiops.narrative }}
{{- if .Values.aiops.narrative.llm }}
{{- if .Values.aiops.narrative.llm.apiKey }}
{{- if .Values.aiops.narrative.llm.apiKey.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "right-sizer.fullname" . }}-llm
  labels:
    {{- include "right-sizer.labels" . | nindent 4 }}
    app.kubernetes.io/component: llm-credentials
  annotations:
    {{- with .Values.aiops.narrative.llm.apiKey.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
{{- if .Values.aiops.narrative.llm.apiKey.value }}
stringData:
  api-key: {{ .Values.aiops.narrative.llm.apiKey.value | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
