{{- if .Values.createDefaultConfig }}
apiVersion: rightsizer.io/v1alpha1
kind: RightSizerConfig
metadata:
  name: {{ .Values.defaultConfig.name | default "default" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "right-sizer.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
spec:
  enabled: {{ .Values.defaultConfig.enabled }}
  defaultMode: {{ .Values.defaultConfig.mode }}
  resizeInterval: {{ .Values.defaultConfig.resizeInterval }}
  dryRun: {{ .Values.defaultConfig.dryRun }}

  defaultResourceStrategy:
    cpu:
      requestMultiplier: {{ .Values.defaultConfig.resourceStrategy.cpu.requestMultiplier }}
      requestAddition: {{ .Values.defaultConfig.resourceStrategy.cpu.requestAddition }}
      limitMultiplier: {{ .Values.defaultConfig.resourceStrategy.cpu.limitMultiplier }}
      limitAddition: {{ .Values.defaultConfig.resourceStrategy.cpu.limitAddition }}
      minRequest: {{ .Values.defaultConfig.resourceStrategy.cpu.minRequest }}
      maxLimit: {{ .Values.defaultConfig.resourceStrategy.cpu.maxLimit }}
    memory:
      requestMultiplier: {{ .Values.defaultConfig.resourceStrategy.memory.requestMultiplier }}
      requestAddition: {{ .Values.defaultConfig.resourceStrategy.memory.requestAddition }}
      limitMultiplier: {{ .Values.defaultConfig.resourceStrategy.memory.limitMultiplier }}
      limitAddition: {{ .Values.defaultConfig.resourceStrategy.memory.limitAddition }}
      minRequest: {{ .Values.defaultConfig.resourceStrategy.memory.minRequest }}
      maxLimit: {{ .Values.defaultConfig.resourceStrategy.memory.maxLimit }}
    historyWindow: "7d"
    percentile: 95
    updateMode: "rolling"

  globalConstraints:
    maxChangePercentage: {{ .Values.defaultConfig.constraints.maxChangePercentage }}
    minChangeThreshold: {{ .Values.defaultConfig.constraints.minChangeThreshold }}
    cooldownPeriod: {{ .Values.defaultConfig.constraints.cooldownPeriod }}
    maxConcurrentResizes: {{ .Values.defaultConfig.constraints.maxConcurrentResizes }}
    maxRestartsPerHour: {{ .Values.defaultConfig.constraints.maxRestartsPerHour }}
    respectPDB: {{ .Values.defaultConfig.constraints.respectPDB }}
    respectHPA: {{ .Values.defaultConfig.constraints.respectHPA }}
    respectVPA: {{ .Values.defaultConfig.constraints.respectVPA }}

  metricsConfig:
    provider: {{ .Values.defaultConfig.metrics.provider }}
    {{- if .Values.defaultConfig.metrics.prometheusEndpoint }}
    prometheusEndpoint: {{ .Values.defaultConfig.metrics.prometheusEndpoint }}
    {{- end }}
    scrapeInterval: {{ .Values.defaultConfig.metrics.scrapeInterval }}
    retentionPeriod: {{ .Values.defaultConfig.metrics.retentionPeriod }}
    enableProfiling: false

  observabilityConfig:
    logLevel: {{ .Values.defaultConfig.observability.logLevel }}
    logFormat: {{ .Values.defaultConfig.observability.logFormat }}
    enableAuditLog: {{ .Values.defaultConfig.observability.enableAuditLog }}
    auditLogPath: {{ .Values.defaultConfig.observability.auditLogPath }}
    enableMetricsExport: {{ .Values.defaultConfig.observability.enableMetricsExport }}
    metricsPort: {{ .Values.defaultConfig.observability.metricsPort }}
    enableTracing: {{ .Values.defaultConfig.observability.enableTracing }}
    {{- if .Values.defaultConfig.observability.tracingEndpoint }}
    tracingEndpoint: {{ .Values.defaultConfig.observability.tracingEndpoint }}
    {{- end }}
    enableEvents: {{ .Values.defaultConfig.observability.enableEvents }}

  securityConfig:
    enableAdmissionController: {{ .Values.defaultConfig.security.enableAdmissionController }}
    admissionWebhookPort: {{ .Values.defaultConfig.security.admissionWebhookPort }}
    requireAnnotation: {{ .Values.defaultConfig.security.requireAnnotation }}
    annotationKey: {{ .Values.defaultConfig.security.annotationKey }}
    enableMutatingWebhook: {{ .Values.defaultConfig.security.enableMutatingWebhook }}
    enableValidatingWebhook: {{ .Values.defaultConfig.security.enableValidatingWebhook }}
    tlsConfig:
      autoGenerate: true
      certSecretName: {{ include "right-sizer.fullname" . }}-webhook-certs

  operatorConfig:
    leaderElection: {{ .Values.defaultConfig.operator.leaderElection }}
    {{- if .Values.defaultConfig.operator.leaderElectionNamespace }}
    leaderElectionNamespace: {{ .Values.defaultConfig.operator.leaderElectionNamespace }}
    {{- else }}
    leaderElectionNamespace: {{ .Release.Namespace }}
    {{- end }}
    leaderElectionID: {{ .Values.defaultConfig.operator.leaderElectionID }}
    maxRetries: {{ .Values.defaultConfig.operator.maxRetries }}
    retryInterval: {{ .Values.defaultConfig.operator.retryInterval }}
    enableCircuitBreaker: {{ .Values.defaultConfig.operator.enableCircuitBreaker }}
    circuitBreakerThreshold: {{ .Values.defaultConfig.operator.circuitBreakerThreshold }}
    reconcileInterval: {{ .Values.defaultConfig.operator.reconcileInterval }}
    workerThreads: {{ .Values.defaultConfig.operator.workerThreads }}

  namespaceConfig:
    {{- if .Values.defaultConfig.namespaces.include }}
    includeNamespaces:
      {{- range .Values.defaultConfig.namespaces.include }}
      - {{ . }}
      {{- end }}
    {{- end }}
    {{- if .Values.defaultConfig.namespaces.exclude }}
    excludeNamespaces:
      {{- range .Values.defaultConfig.namespaces.exclude }}
      - {{ . }}
      {{- end }}
    {{- end }}
    {{- if .Values.defaultConfig.namespaces.systemNamespaces }}
    systemNamespaces:
      {{- range .Values.defaultConfig.namespaces.systemNamespaces }}
      - {{ . }}
      {{- end }}
    {{- end }}

  {{- if .Values.defaultConfig.featureGates }}
  featureGates:
    {{- range $key, $value := .Values.defaultConfig.featureGates }}
    {{ $key }}: {{ $value }}
    {{- end }}
  {{- end }}
{{- end }}
