prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    podMonitorSelector: {}
    # Enable data persistence for Prometheus
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
    retention: 30d

grafana:
  enabled: true
  adminPassword: admin123
  service:
    type: NodePort
    nodePort: 32000
  # Enable persistence for Grafana dashboards and data
  persistence:
    enabled: true
    storageClassName: standard
    size: 5Gi
    accessModes:
      - ReadWriteOnce

  # Enable anonymous access for demo
  grafana.ini:
    auth.anonymous:
      enabled: true
      org_role: Viewer
    server:
      domain: localhost
      root_url: http://localhost:32000

alertmanager:
  enabled: false

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheusOperator:
  enabled: true
