prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    podMonitorSelector: {}
    # Simplified persistence for Minikube
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
    retention: 7d

grafana:
  enabled: true
  adminPassword: admin123
  service:
    type: NodePort
    nodePort: 32000
  # Simplified persistence for Grafana
  persistence:
    enabled: true
    size: 1Gi
    accessModes:
      - ReadWriteOnce

  # Enable anonymous access for demo
  grafana.ini:
    auth.anonymous:
      enabled: true
      org_role: Viewer
    server:
      domain: localhost
      root_url: http://localhost:32000

alertmanager:
  enabled: false

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheusOperator:
  enabled: true
