apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: right-sizer-metrics
  namespace: right-sizer
  labels:
    app.kubernetes.io/name: right-sizer
    app.kubernetes.io/instance: right-sizer
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: right-sizer
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
---
apiVersion: v1
kind: Service
metadata:
  name: right-sizer-metrics
  namespace: right-sizer
  labels:
    app.kubernetes.io/name: right-sizer
    app.kubernetes.io/instance: right-sizer
spec:
  type: ClusterIP
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  selector:
    app.kubernetes.io/name: right-sizer
