apiVersion: v1
kind: ConfigMap
metadata:
  name: api-proxy-config
  namespace: right-sizer
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 8082;

        # Proxy optimization-events to our real data service
        location /api/optimization-events {
          proxy_pass http://optimization-events-server.right-sizer.svc.cluster.local/events.json;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }

        # Proxy all other API calls to the original right-sizer
        location /api/ {
          proxy_pass http://right-sizer.right-sizer.svc.cluster.local:8082;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }

        # Proxy root requests to right-sizer
        location / {
          proxy_pass http://right-sizer.right-sizer.svc.cluster.local:8082;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-proxy
  namespace: right-sizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-proxy
  template:
    metadata:
      labels:
        app: api-proxy
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 8082
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
      volumes:
      - name: nginx-config
        configMap:
          name: api-proxy-config
---
apiVersion: v1
kind: Service
metadata:
  name: api-proxy
  namespace: right-sizer
spec:
  selector:
    app: api-proxy
  ports:
  - name: api
    port: 8082
    targetPort: 8082
