apiVersion: v1
kind: ServiceAccount
metadata:
  name: right-sizer
  namespace: right-sizer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: right-sizer
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/status", "pods/eviction", "pods/log"]
    verbs: ["get", "list", "watch", "update", "patch", "delete", "create"]
  - apiGroups: [""]
    resources: ["pods/resize"]
    verbs: ["patch", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets", "replicasets"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods", "nodes"]
    verbs: ["get", "list"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["autoscaling.k8s.io"]
    resources: ["verticalpodautoscalers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["rightsizer.io"]
    resources: ["rightsizerconfigs", "rightsizerpolicies"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["rightsizer.io"]
    resources: ["rightsizerconfigs/status", "rightsizerpolicies/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["rightsizer.io"]
    resources: ["rightsizerconfigs/finalizers", "rightsizerpolicies/finalizers"]
    verbs: ["update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: right-sizer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: right-sizer
subjects:
  - kind: ServiceAccount
    name: right-sizer
    namespace: right-sizer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: right-sizer
  namespace: right-sizer
  labels:
    app: right-sizer
    app.kubernetes.io/name: right-sizer
    app.kubernetes.io/instance: right-sizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: right-sizer
      app.kubernetes.io/name: right-sizer
      app.kubernetes.io/instance: right-sizer
  template:
    metadata:
      labels:
        app: right-sizer
        app.kubernetes.io/name: right-sizer
        app.kubernetes.io/instance: right-sizer
    spec:
      serviceAccountName: right-sizer
      containers:
        - name: right-sizer
          image: right-sizer:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: health
              containerPort: 8081
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
            - name: api
              containerPort: 8082
              protocol: TCP
          env:
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LOG_LEVEL
              value: "info"
            - name: METRICS_PORT
              value: "9090"
            - name: API_PORT
              value: "8082"
            - name: HEALTH_PORT
              value: "8081"
            - name: ENABLE_LEADER_ELECTION
              value: "false"
            - name: RESYNC_PERIOD
              value: "30s"
            - name: MIN_MEMORY
              value: "64Mi"
            - name: MIN_CPU
              value: "10m"
            - name: MEMORY_BUFFER_PERCENTAGE
              value: "10"
            - name: CPU_BUFFER_PERCENTAGE
              value: "10"
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65532
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        fsGroup: 65532
---
apiVersion: v1
kind: Service
metadata:
  name: right-sizer
  namespace: right-sizer
  labels:
    app: right-sizer
    app.kubernetes.io/name: right-sizer
    app.kubernetes.io/instance: right-sizer
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: 8082
      targetPort: api
      protocol: TCP
      name: api
  selector:
    app: right-sizer
    app.kubernetes.io/name: right-sizer
    app.kubernetes.io/instance: right-sizer
