apiVersion: v1
kind: Pod
metadata:
  name: cpu-stress-test
  namespace: test-workloads
  labels:
    app: stress-test
    rightsizer.io/enable: "true"
spec:
  containers:
  - name: stress
    image: progrium/stress
    args:
    - "--cpu"
    - "1"
    - "--timeout"
    - "120s"
    resources:
      requests:
        cpu: "100m"
        memory: "64Mi"
      limits:
        cpu: "500m"
        memory: "128Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: memory-stress-test
  namespace: test-workloads
  labels:
    app: stress-test
    rightsizer.io/enable: "true"
spec:
  containers:
  - name: memory-consumer
    image: polinux/stress
    command: ["stress"]
    args:
    - "--vm"
    - "1"
    - "--vm-bytes"
    - "150M"
    - "--vm-hang"
    - "1"
    - "--timeout"
    - "120s"
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "100m"
        memory: "256Mi"
