apiVersion: rightsizer.io/v1alpha1
kind: RightSizerConfig
metadata:
  name: right-sizer-config-with-thresholds
  namespace: right-sizer-system
spec:
  # Enable the operator
  enabled: true

  # Set the mode - can be "conservative", "balanced", or "aggressive"
  defaultMode: "balanced"

  # How often to check and resize resources
  resizeInterval: "30s"

  # Set to true to only log recommendations without applying changes
  dryRun: false

  # Default resource calculation strategy
  defaultResourceStrategy:
    cpu:
      # Multipliers and additions for calculating resources
      requestMultiplier: 1.2     # Add 20% buffer to CPU requests
      requestAddition: 0         # No fixed addition
      limitMultiplier: 2.0       # Limits are 2x requests
      limitAddition: 0           # No fixed addition
      minRequest: 10             # Minimum 10 millicores
      maxLimit: 4000             # Maximum 4 cores

      # Scaling thresholds - NEW FEATURE
      scaleUpThreshold: 0.8      # Scale up when CPU usage exceeds 80% of limit
      scaleDownThreshold: 0.3    # Scale down when CPU usage is below 30% of limit

    memory:
      # Multipliers and additions for calculating resources
      requestMultiplier: 1.2     # Add 20% buffer to memory requests
      requestAddition: 0         # No fixed addition in MB
      limitMultiplier: 2.0       # Limits are 2x requests
      limitAddition: 0           # No fixed addition in MB
      minRequest: 64             # Minimum 64 MB
      maxLimit: 8192             # Maximum 8 GB

      # Scaling thresholds - NEW FEATURE
      scaleUpThreshold: 0.8      # Scale up when memory usage exceeds 80% of limit
      scaleDownThreshold: 0.3    # Scale down when memory usage is below 30% of limit

  # Global constraints for safety
  globalConstraints:
    maxChangePercentage: 50        # Don't change resources by more than 50%
    minChangeThreshold: 5          # Ignore changes less than 5%
    cooldownPeriod: "5m"           # Wait 5 minutes between adjustments
    maxConcurrentResizes: 10       # Limit concurrent operations
    maxRestartsPerHour: 3          # Limit pod restarts
    respectPDB: true               # Respect PodDisruptionBudgets
    respectHPA: true               # Don't conflict with HPA
    respectVPA: false              # We replace VPA functionality

  # Metrics configuration
  metricsConfig:
    provider: "metrics-server"     # Can be "metrics-server" or "prometheus"
    scrapeInterval: "30s"          # How often to collect metrics
    retentionPeriod: "7d"          # Keep metrics for 7 days
    enableProfiling: false         # Performance profiling

  # Observability configuration
  observabilityConfig:
    logLevel: "info"               # Log level: debug, info, warn, error
    logFormat: "json"              # Output format: json or text
    enableAuditLog: true           # Track all resource changes
    enableMetricsExport: true      # Export Prometheus metrics
    metricsPort: 9090              # Port for metrics endpoint
    enableEvents: true             # Create Kubernetes events

  # Operator behavior configuration
  operatorConfig:
    maxRetries: 3                  # Retry failed operations
    retryInterval: "5s"            # Wait between retries
    maxConcurrentReconciles: 3     # Parallel processing
    qps: 20                        # API queries per second
    burst: 30                      # API burst capacity

  # Namespace filtering
  namespaceConfig:
    # Only process these namespaces (empty = all)
    includeNamespaces: []
    # Never process these namespaces
    excludeNamespaces:
      - kube-system
      - kube-public
      - kube-node-lease
      - cert-manager
      - istio-system

  # Feature gates for experimental features
  featureGates:
    EnableInPlaceResize: true      # Use Kubernetes 1.27+ in-place resize

---
# Example demonstrating custom thresholds for different environments
apiVersion: rightsizer.io/v1alpha1
kind: RightSizerConfig
metadata:
  name: production-config
  namespace: right-sizer-system
spec:
  enabled: true
  defaultMode: "conservative"
  resizeInterval: "1m"
  dryRun: false

  defaultResourceStrategy:
    cpu:
      requestMultiplier: 1.3       # More buffer for production
      limitMultiplier: 2.5         # Higher burst capacity
      minRequest: 50               # Higher minimum
      maxLimit: 8000               # Higher maximum

      # Conservative thresholds for production
      scaleUpThreshold: 0.7        # Scale up earlier at 70%
      scaleDownThreshold: 0.2      # Only scale down when very low (20%)

    memory:
      requestMultiplier: 1.3       # More buffer for production
      limitMultiplier: 2.5         # Higher burst capacity
      minRequest: 128              # Higher minimum
      maxLimit: 16384              # Higher maximum

      # Conservative thresholds for production
      scaleUpThreshold: 0.7        # Scale up earlier at 70%
      scaleDownThreshold: 0.2      # Only scale down when very low (20%)

  globalConstraints:
    maxChangePercentage: 30        # Smaller changes in production
    minChangeThreshold: 10         # Ignore smaller changes
    cooldownPeriod: "10m"          # Longer cooldown
    maxRestartsPerHour: 2          # Fewer restarts allowed

---
# Example for development environment with aggressive scaling
apiVersion: rightsizer.io/v1alpha1
kind: RightSizerConfig
metadata:
  name: development-config
  namespace: right-sizer-system
spec:
  enabled: true
  defaultMode: "aggressive"
  resizeInterval: "15s"           # More frequent checks
  dryRun: false

  defaultResourceStrategy:
    cpu:
      requestMultiplier: 1.1       # Minimal buffer
      limitMultiplier: 1.5         # Lower burst capacity
      minRequest: 5                # Very low minimum
      maxLimit: 2000               # Lower maximum

      # Aggressive thresholds for development
      scaleUpThreshold: 0.9        # Only scale up when very high (90%)
      scaleDownThreshold: 0.5      # Scale down aggressively at 50%

    memory:
      requestMultiplier: 1.1       # Minimal buffer
      limitMultiplier: 1.5         # Lower burst capacity
      minRequest: 32               # Very low minimum
      maxLimit: 4096               # Lower maximum

      # Aggressive thresholds for development
      scaleUpThreshold: 0.9        # Only scale up when very high (90%)
      scaleDownThreshold: 0.5      # Scale down aggressively at 50%

  globalConstraints:
    maxChangePercentage: 75        # Allow larger changes
    minChangeThreshold: 2          # Apply even small changes
    cooldownPeriod: "1m"           # Short cooldown
    maxRestartsPerHour: 10         # More restarts allowed
