// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: api/grpc/v1/rightsizer.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClusterStatus int32

const (
	ClusterStatus_CLUSTER_STATUS_UNKNOWN   ClusterStatus = 0
	ClusterStatus_CLUSTER_STATUS_HEALTHY   ClusterStatus = 1
	ClusterStatus_CLUSTER_STATUS_DEGRADED  ClusterStatus = 2
	ClusterStatus_CLUSTER_STATUS_UNHEALTHY ClusterStatus = 3
)

// Enum value maps for ClusterStatus.
var (
	ClusterStatus_name = map[int32]string{
		0: "CLUSTER_STATUS_UNKNOWN",
		1: "CLUSTER_STATUS_HEALTHY",
		2: "CLUSTER_STATUS_DEGRADED",
		3: "CLUSTER_STATUS_UNHEALTHY",
	}
	ClusterStatus_value = map[string]int32{
		"CLUSTER_STATUS_UNKNOWN":   0,
		"CLUSTER_STATUS_HEALTHY":   1,
		"CLUSTER_STATUS_DEGRADED":  2,
		"CLUSTER_STATUS_UNHEALTHY": 3,
	}
)

func (x ClusterStatus) Enum() *ClusterStatus {
	p := new(ClusterStatus)
	*p = x
	return p
}

func (x ClusterStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClusterStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_grpc_v1_rightsizer_proto_enumTypes[0].Descriptor()
}

func (ClusterStatus) Type() protoreflect.EnumType {
	return &file_api_grpc_v1_rightsizer_proto_enumTypes[0]
}

func (x ClusterStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClusterStatus.Descriptor instead.
func (ClusterStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_grpc_v1_rightsizer_proto_rawDescGZIP(), []int{0}
}

type MetricType int32

const (
	MetricType_METRIC_TYPE_ALL         MetricType = 0
	MetricType_METRIC_TYPE_RESOURCE    MetricType = 1
	MetricType_METRIC_TYPE_PERFORMANCE MetricType = 2
	MetricType_METRIC_TYPE_USAGE       MetricType = 3
)

// Enum value maps for MetricType.
var (
	MetricType_name = map[int32]string{
		0: "METRIC_TYPE_ALL",
		1: "METRIC_TYPE_RESOURCE",
		2: "METRIC_TYPE_PERFORMANCE",
		3: "METRIC_TYPE_USAGE",
	}
	MetricType_value = map[string]int32{
		"METRIC_TYPE_ALL":         0,
		"METRIC_TYPE_RESOURCE":    1,
		"METRIC_TYPE_PERFORMANCE": 2,
		"METRIC_TYPE_USAGE":       3,
	}
)

func (x MetricType) Enum() *MetricType {
	p := new(MetricType)
	*p = x
	return p
}

func (x MetricType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_grpc_v1_rightsizer_proto_enumTypes[1].Descriptor()
}

func (MetricType) Type() protoreflect.EnumType {
	return &file_api_grpc_v1_rightsizer_proto_enumTypes[1]
}

func (x MetricType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricType.Descriptor instead.
func (MetricType) EnumDescriptor() ([]byte, []int) {
	return file_api_grpc_v1_rightsizer_proto_rawDescGZIP(), []int{1}
}

type EventType int32

const (
	EventType_EVENT_TYPE_ALL                 EventType = 0
	EventType_EVENT_TYPE_POD_CREATED         EventType = 1
	EventType_EVENT_TYPE_POD_DELETED         EventType = 2
	EventType_EVENT_TYPE_POD_OOM_KILLED      EventType = 3
	EventType_EVENT_TYPE_RESOURCE_EXHAUSTION EventType = 4
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_ALL",
		1: "EVENT_TYPE_POD_CREATED",
		2: "EVENT_TYPE_POD_DELETED",
		3: "EVENT_TYPE_POD_OOM_KILLED",
		4: "EVENT_TYPE_RESOURCE_EXHAUSTION",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_ALL":                 0,
		"EVENT_TYPE_POD_CREATED":         1,
		"EVENT_TYPE_POD_DELETED":         2,
		"EVENT_TYPE_POD_OOM_KILLED":      3,
		"EVENT_TYPE_RESOURCE_EXHAUSTION": 4,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_grpc_v1_rightsizer_proto_enumTypes[2].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_api_grpc_v1_rightsizer_proto_enumTypes[2]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_api_grpc_v1_rightsizer_proto_rawDescGZIP(), []int{2}
}

type Severity int32

const (
	Severity_SEVERITY_INFO     Severity = 0
	Severity_SEVERITY_WARNING  Severity = 1
	Severity_SEVERITY_ERROR    Severity = 2
	Severity_SEVERITY_CRITICAL Severity = 3
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_INFO",
		1: "SEVERITY_WARNING",
		2: "SEVERITY_ERROR",
		3: "SEVERITY_CRITICAL",
	}
	Severity_value = map[string]int32{
		"SEVERITY_INFO":     0,
		"SEVERITY_WARNING":  1,
		"SEVERITY_ERROR":    2,
		"SEVERITY_CRITICAL": 3,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_api_grpc_v1_rightsizer_proto_enumTypes[3].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_api_grpc_v1_rightsizer_proto_enumTypes[3]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_api_grpc_v1_rightsizer_proto_rawDescGZIP(), []int{3}
}

type ActionStatus int32

const (
	ActionStatus_ACTION_STATUS_PENDING   ActionStatus = 0
	ActionStatus_ACTION_STATUS_RUNNING   ActionStatus = 1
	ActionStatus_ACTION_STATUS_COMPLETED ActionStatus = 2
	ActionStatus_ACTION_STATUS_FAILED    ActionStatus = 3
	ActionStatus_ACTION_STATUS_CANCELLED ActionStatus = 4
)

// Enum value maps for ActionStatus.
var (
	ActionStatus_name = map[int32]string{
		0: "ACTION_STATUS_PENDING",
		1: "ACTION_STATUS_RUNNING",
		2: "ACTION_STATUS_COMPLETED",
		3: "ACTION_STATUS_FAILED",
		4: "ACTION_STATUS_CANCELLED",
	}
	ActionStatus_value = map[string]int32{
		"ACTION_STATUS_PENDING":   0,
		"ACTION_STATUS_RUNNING":   1,
		"ACTION_STATUS_COMPLETED": 2,
		"ACTION_STATUS_FAILED":    3,
		"ACTION_STATUS_CANCELLED": 4,
	}
)

func (x ActionStatus) Enum() *ActionStatus {
	p := new(ActionStatus)
	*p = x
	return p
}

func (x ActionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_grpc_v1_rightsizer_proto_enumTypes[4].Descriptor()
}

func (ActionStatus) Type() protoreflect.EnumType {
	return &file_api_grpc_v1_rightsizer_proto_enumTypes[4]
}

func (x ActionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionStatus.Descriptor instead.
func (ActionStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_grpc_v1_rightsizer_proto_rawDescGZIP(), []int{4}
}

type RiskLevel int32

const (
	RiskLevel_RISK_LEVEL_LOW    RiskLevel = 0
	RiskLevel_RISK_LEVEL_MEDIUM RiskLevel = 1
	RiskLevel_RISK_LEVEL_HIGH   RiskLevel = 2
)

// Enum value maps for RiskLevel.
var (
	RiskLevel_name = map[int32]string{
		0: "RISK_LEVEL_LOW",
		1: "RISK_LEVEL_MEDIUM",
		2: "RISK_LEVEL_HIGH",
	}
	RiskLevel_value = map[string]int32{
		"RISK_LEVEL_LOW":    0,
		"RISK_LEVEL_MEDIUM": 1,
		"RISK_LEVEL_HIGH":   2,
	}
)

func (x RiskLevel) Enum() *RiskLevel {
	p := new(RiskLevel)
	*p = x
	return p
}

func (x RiskLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RiskLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_api_grpc_v1_rightsizer_proto_enumTypes[5].Descriptor()
}

func (RiskLevel) Type() protoreflect.EnumType {
	return &file_api_grpc_v1_rightsizer_proto_enumTypes[5]
}

func (x RiskLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RiskLevel.Descriptor instead.
func (RiskLevel) EnumDescriptor() ([]byte, []int) {
	return file_api_grpc_v1_rightsizer_proto_rawDescGZIP(), []int{5}
}

type Priority int32

const (
	Priority_PRIORITY_LOW      Priority = 0
	Priority_PRIORITY_MEDIUM   Priority = 1
	Priority_PRIORITY_HIGH     Priority = 2
	Priority_PRIORITY_CRITICAL Priority = 3
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "PRIORITY_LOW",
		1: "PRIORITY_MEDIUM",
		2: "PRIORITY_HIGH",
		3: "PRIORITY_CRITICAL",
	}
	Priority_value = map[string]int32{
		"PRIORITY_LOW":      0,
		"PRIORITY_MEDIUM":   1,
		"PRIORITY_HIGH":     2,
		"PRIORITY_CRITICAL": 3,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_api_grpc_v1_rightsizer_proto_enumTypes[6].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_api_grpc_v1_rightsizer_proto_enumTypes[6]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_api_grpc_v1_rightsizer_proto_rawDescGZIP(), []int{6}
}

type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNKNOWN     HealthStatus = 0
	HealthStatus_HEALTH_STATUS_SERVING     HealthStatus = 1
	HealthStatus_HEALTH_STATUS_NOT_SERVING HealthStatus = 2
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNKNOWN",
		1: "HEALTH_STATUS_SERVING",
		2: "HEALTH_STATUS_NOT_SERVING",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNKNOWN":     0,
		"HEALTH_STATUS_SERVING":     1,
		"HEALTH_STATUS_NOT_SERVING": 2,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_grpc_v1_rightsizer_proto_enumTypes[7].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_api_grpc_v1_rightsizer_proto_enumTypes[7]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_grpc_v1_rightsizer_proto_rawDescGZIP(), []int{7}
}

// Cluster information
type ClusterInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Environment   string                 `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Capabilities  []string               `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Status        ClusterStatus          `protobuf:"varint,6,opt,name=status,proto3,enum=rightsizer.v1.ClusterStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterInfo) Reset() {
	*x = ClusterInfo{}
	mi := &file_api_grpc_v1_rightsizer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterInfo) ProtoMessage() {}

func (x *ClusterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_rightsizer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterInfo.ProtoReflect.Descriptor instead.
func (*ClusterInfo) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_rightsizer_proto_rawDescGZIP(), []int{0}
}

func (x *ClusterInfo) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ClusterInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClusterInfo) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *ClusterInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ClusterInfo) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ClusterInfo) GetStatus() ClusterStatus {
	if x != nil {
		return x.Status
	}
	return ClusterStatus_CLUSTER_STATUS_UNKNOWN
}

// Metrics
type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MetricType             `protobuf:"varint,1,opt,name=type,proto3,enum=rightsizer.v1.MetricType" json:"type,omitempty"`
	Since         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=since,proto3" json:"since,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PodName       string                 `protobuf:"bytes,4,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_api_grpc_v1_rightsizer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_rightsizer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_rightsizer_proto_rawDescGZIP(), []int{1}
}

func (x *MetricsRequest) GetType() MetricType {
	if x != nil {
		return x.Type
	}
	return MetricType_METRIC_TYPE_ALL
}

func (x *MetricsRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *MetricsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *MetricsRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

type MetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*Metric              `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_api_grpc_v1_rightsizer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_rightsizer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_rightsizer_proto_rawDescGZIP(), []int{2}
}

func (x *MetricsResponse) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *MetricsResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Unit          string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_api_grpc_v1_rightsizer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_rightsizer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_rightsizer_proto_rawDescGZIP(), []int{3}
}

func (x *Metric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Metric) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Metric) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Metric) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// Events
type EventStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventTypes    []EventType            `protobuf:"varint,1,rep,packed,name=event_types,json=eventTypes,proto3,enum=rightsizer.v1.EventType" json:"event_types,omitempty"`
	Namespaces    []string               `protobuf:"bytes,2,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	PodNames      []string               `protobuf:"bytes,3,rep,name=pod_names,json=podNames,proto3" json:"pod_names,omitempty"`
	Severities    []Severity             `protobuf:"varint,4,rep,packed,name=severities,proto3,enum=rightsizer.v1.Severity" json:"severities,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventStreamRequest) Reset() {
	*x = EventStreamRequest{}
	mi := &file_api_grpc_v1_rightsizer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventStreamRequest) ProtoMessage() {}

func (x *EventStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_rightsizer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventStreamRequest.ProtoReflect.Descriptor instead.
func (*EventStreamRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_rightsizer_proto_rawDescGZIP(), []int{4}
}

func (x *EventStreamRequest) GetEventTypes() []EventType {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

func (x *EventStreamRequest) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *EventStreamRequest) GetPodNames() []string {
	if x != nil {
		return x.PodNames
	}
	return nil
}

func (x *EventStreamRequest) GetSeverities() []Severity {
	if x != nil {
		return x.Severities
	}
	return nil
}

func (x *EventStreamRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type EventStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventStreamResponse) Reset() {
	*x = EventStreamResponse{}
	mi := &file_api_grpc_v1_rightsizer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventStreamResponse) ProtoMessage() {}

func (x *EventStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_rightsizer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventStreamResponse.ProtoReflect.Descriptor instead.
func (*EventStreamResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_rightsizer_proto_rawDescGZIP(), []int{5}
}

func (x *EventStreamResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	ClusterId     string                 `protobuf:"bytes,3,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Namespace     string                 `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ResourceName  string                 `protobuf:"bytes,5,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	Severity      Severity               `protobuf:"varint,6,opt,name=severity,proto3,enum=rightsizer.v1.Severity" json:"severity,omitempty"`
	Message       string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Details       map[string]string      `protobuf:"bytes,9,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tags          []string               `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	CorrelationId string                 `protobuf:"bytes,11,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_api_grpc_v1_rightsizer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_rightsizer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_rightsizer_proto_rawDescGZIP(), []int{6}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *Event) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Event) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *Event) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_INFO
}

func (x *Event) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Event) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Event) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *Event) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Event) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

// Actions
type ActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        *Action                `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionRequest) Reset() {
	*x = ActionRequest{}
	mi := &file_api_grpc_v1_rightsizer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionRequest) ProtoMessage() {}

func (x *ActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_rightsizer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionRequest.ProtoReflect.Descriptor instead.
func (*ActionRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_rightsizer_proto_rawDescGZIP(), []int{7}
}

func (x *ActionRequest) GetAction() *Action {
	if x != nil {
		return x.Action
	}
	return nil
}

type ActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ActionId      string                 `protobuf:"bytes,3,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResponse) Reset() {
	*x = ActionResponse{}
	mi := &file_api_grpc_v1_rightsizer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse) ProtoMessage() {}

func (x *ActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_rightsizer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse.ProtoReflect.Descriptor instead.
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_rightsizer_proto_rawDescGZIP(), []int{8}
}

func (x *ActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ActionResponse) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

type ActionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionId      string                 `protobuf:"bytes,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionStatusRequest) Reset() {
	*x = ActionStatusRequest{}
	mi := &file_api_grpc_v1_rightsizer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionStatusRequest) ProtoMessage() {}

func (x *ActionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_rightsizer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionStatusRequest.ProtoReflect.Descriptor instead.
func (*ActionStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_rightsizer_proto_rawDescGZIP(), []int{9}
}

func (x *ActionStatusRequest) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

type ActionStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ActionStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=rightsizer.v1.ActionStatus" json:"status,omitempty"`
	Result        string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionStatusResponse) Reset() {
	*x = ActionStatusResponse{}
	mi := &file_api_grpc_v1_rightsizer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionStatusResponse) ProtoMessage() {}

func (x *ActionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_rightsizer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionStatusResponse.ProtoReflect.Descriptor instead.
func (*ActionStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_rightsizer_proto_rawDescGZIP(), []int{10}
}

func (x *ActionStatusResponse) GetStatus() ActionStatus {
	if x != nil {
		return x.Status
	}
	return ActionStatus_ACTION_STATUS_PENDING
}

func (x *ActionStatusResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ActionStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ActionStatusResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Action struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Target         *ActionTarget          `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Parameters     map[string]string      `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Risk           RiskLevel              `protobuf:"varint,5,opt,name=risk,proto3,enum=rightsizer.v1.RiskLevel" json:"risk,omitempty"`
	Reason         string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	Priority       Priority               `protobuf:"varint,7,opt,name=priority,proto3,enum=rightsizer.v1.Priority" json:"priority,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,8,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_api_grpc_v1_rightsizer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_rightsizer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_rightsizer_proto_rawDescGZIP(), []int{11}
}

func (x *Action) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Action) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Action) GetTarget() *ActionTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *Action) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *Action) GetRisk() RiskLevel {
	if x != nil {
		return x.Risk
	}
	return RiskLevel_RISK_LEVEL_LOW
}

func (x *Action) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Action) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_LOW
}

func (x *Action) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type ActionTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Container     string                 `protobuf:"bytes,4,opt,name=container,proto3" json:"container,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionTarget) Reset() {
	*x = ActionTarget{}
	mi := &file_api_grpc_v1_rightsizer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionTarget) ProtoMessage() {}

func (x *ActionTarget) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_rightsizer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionTarget.ProtoReflect.Descriptor instead.
func (*ActionTarget) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_rightsizer_proto_rawDescGZIP(), []int{12}
}

func (x *ActionTarget) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ActionTarget) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActionTarget) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ActionTarget) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

// Health
type HealthResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Status        HealthStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=rightsizer.v1.HealthStatus" json:"status,omitempty"`
	Checks        map[string]HealthStatus `protobuf:"bytes,2,rep,name=checks,proto3" json:"checks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=rightsizer.v1.HealthStatus"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_grpc_v1_rightsizer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_rightsizer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_rightsizer_proto_rawDescGZIP(), []int{13}
}

func (x *HealthResponse) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_STATUS_UNKNOWN
}

func (x *HealthResponse) GetChecks() map[string]HealthStatus {
	if x != nil {
		return x.Checks
	}
	return nil
}

var File_api_grpc_v1_rightsizer_proto protoreflect.FileDescriptor

const file_api_grpc_v1_rightsizer_proto_rawDesc = "" +
	"\n" +
	"\x1capi/grpc/v1/rightsizer.proto\x12\rrightsizer.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd6\x01\n" +
	"\vClusterInfo\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\venvironment\x18\x03 \x01(\tR\venvironment\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\x124\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1c.rightsizer.v1.ClusterStatusR\x06status\"\xaa\x01\n" +
	"\x0eMetricsRequest\x12-\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.rightsizer.v1.MetricTypeR\x04type\x120\n" +
	"\x05since\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x19\n" +
	"\bpod_name\x18\x04 \x01(\tR\apodName\"|\n" +
	"\x0fMetricsResponse\x12/\n" +
	"\ametrics\x18\x01 \x03(\v2\x15.rightsizer.v1.MetricR\ametrics\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xf6\x01\n" +
	"\x06Metric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x129\n" +
	"\x06labels\x18\x05 \x03(\v2!.rightsizer.v1.Metric.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd9\x01\n" +
	"\x12EventStreamRequest\x129\n" +
	"\vevent_types\x18\x01 \x03(\x0e2\x18.rightsizer.v1.EventTypeR\n" +
	"eventTypes\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x02 \x03(\tR\n" +
	"namespaces\x12\x1b\n" +
	"\tpod_names\x18\x03 \x03(\tR\bpodNames\x127\n" +
	"\n" +
	"severities\x18\x04 \x03(\x0e2\x17.rightsizer.v1.SeverityR\n" +
	"severities\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\"A\n" +
	"\x13EventStreamResponse\x12*\n" +
	"\x05event\x18\x01 \x01(\v2\x14.rightsizer.v1.EventR\x05event\"\xca\x03\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x03 \x01(\tR\tclusterId\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12#\n" +
	"\rresource_name\x18\x05 \x01(\tR\fresourceName\x123\n" +
	"\bseverity\x18\x06 \x01(\x0e2\x17.rightsizer.v1.SeverityR\bseverity\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12;\n" +
	"\adetails\x18\t \x03(\v2!.rightsizer.v1.Event.DetailsEntryR\adetails\x12\x12\n" +
	"\x04tags\x18\n" +
	" \x03(\tR\x04tags\x12%\n" +
	"\x0ecorrelation_id\x18\v \x01(\tR\rcorrelationId\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\">\n" +
	"\rActionRequest\x12-\n" +
	"\x06action\x18\x01 \x01(\v2\x15.rightsizer.v1.ActionR\x06action\"a\n" +
	"\x0eActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\taction_id\x18\x03 \x01(\tR\bactionId\"2\n" +
	"\x13ActionStatusRequest\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\tR\bactionId\"\xb4\x01\n" +
	"\x14ActionStatusResponse\x123\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1b.rightsizer.v1.ActionStatusR\x06status\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x8b\x03\n" +
	"\x06Action\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x123\n" +
	"\x06target\x18\x03 \x01(\v2\x1b.rightsizer.v1.ActionTargetR\x06target\x12E\n" +
	"\n" +
	"parameters\x18\x04 \x03(\v2%.rightsizer.v1.Action.ParametersEntryR\n" +
	"parameters\x12,\n" +
	"\x04risk\x18\x05 \x01(\x0e2\x18.rightsizer.v1.RiskLevelR\x04risk\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x123\n" +
	"\bpriority\x18\a \x01(\x0e2\x17.rightsizer.v1.PriorityR\bpriority\x12'\n" +
	"\x0ftimeout_seconds\x18\b \x01(\x05R\x0etimeoutSeconds\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"r\n" +
	"\fActionTarget\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x1c\n" +
	"\tcontainer\x18\x04 \x01(\tR\tcontainer\"\xe0\x01\n" +
	"\x0eHealthResponse\x123\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1b.rightsizer.v1.HealthStatusR\x06status\x12A\n" +
	"\x06checks\x18\x02 \x03(\v2).rightsizer.v1.HealthResponse.ChecksEntryR\x06checks\x1aV\n" +
	"\vChecksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\x0e2\x1b.rightsizer.v1.HealthStatusR\x05value:\x028\x01*\x82\x01\n" +
	"\rClusterStatus\x12\x1a\n" +
	"\x16CLUSTER_STATUS_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16CLUSTER_STATUS_HEALTHY\x10\x01\x12\x1b\n" +
	"\x17CLUSTER_STATUS_DEGRADED\x10\x02\x12\x1c\n" +
	"\x18CLUSTER_STATUS_UNHEALTHY\x10\x03*o\n" +
	"\n" +
	"MetricType\x12\x13\n" +
	"\x0fMETRIC_TYPE_ALL\x10\x00\x12\x18\n" +
	"\x14METRIC_TYPE_RESOURCE\x10\x01\x12\x1b\n" +
	"\x17METRIC_TYPE_PERFORMANCE\x10\x02\x12\x15\n" +
	"\x11METRIC_TYPE_USAGE\x10\x03*\x9a\x01\n" +
	"\tEventType\x12\x12\n" +
	"\x0eEVENT_TYPE_ALL\x10\x00\x12\x1a\n" +
	"\x16EVENT_TYPE_POD_CREATED\x10\x01\x12\x1a\n" +
	"\x16EVENT_TYPE_POD_DELETED\x10\x02\x12\x1d\n" +
	"\x19EVENT_TYPE_POD_OOM_KILLED\x10\x03\x12\"\n" +
	"\x1eEVENT_TYPE_RESOURCE_EXHAUSTION\x10\x04*^\n" +
	"\bSeverity\x12\x11\n" +
	"\rSEVERITY_INFO\x10\x00\x12\x14\n" +
	"\x10SEVERITY_WARNING\x10\x01\x12\x12\n" +
	"\x0eSEVERITY_ERROR\x10\x02\x12\x15\n" +
	"\x11SEVERITY_CRITICAL\x10\x03*\x98\x01\n" +
	"\fActionStatus\x12\x19\n" +
	"\x15ACTION_STATUS_PENDING\x10\x00\x12\x19\n" +
	"\x15ACTION_STATUS_RUNNING\x10\x01\x12\x1b\n" +
	"\x17ACTION_STATUS_COMPLETED\x10\x02\x12\x18\n" +
	"\x14ACTION_STATUS_FAILED\x10\x03\x12\x1b\n" +
	"\x17ACTION_STATUS_CANCELLED\x10\x04*K\n" +
	"\tRiskLevel\x12\x12\n" +
	"\x0eRISK_LEVEL_LOW\x10\x00\x12\x15\n" +
	"\x11RISK_LEVEL_MEDIUM\x10\x01\x12\x13\n" +
	"\x0fRISK_LEVEL_HIGH\x10\x02*[\n" +
	"\bPriority\x12\x10\n" +
	"\fPRIORITY_LOW\x10\x00\x12\x13\n" +
	"\x0fPRIORITY_MEDIUM\x10\x01\x12\x11\n" +
	"\rPRIORITY_HIGH\x10\x02\x12\x15\n" +
	"\x11PRIORITY_CRITICAL\x10\x03*c\n" +
	"\fHealthStatus\x12\x19\n" +
	"\x15HEALTH_STATUS_UNKNOWN\x10\x00\x12\x19\n" +
	"\x15HEALTH_STATUS_SERVING\x10\x01\x12\x1d\n" +
	"\x19HEALTH_STATUS_NOT_SERVING\x10\x022\xef\x03\n" +
	"\x11RightSizerService\x12D\n" +
	"\x0eGetClusterInfo\x12\x16.google.protobuf.Empty\x1a\x1a.rightsizer.v1.ClusterInfo\x12K\n" +
	"\n" +
	"GetMetrics\x12\x1d.rightsizer.v1.MetricsRequest\x1a\x1e.rightsizer.v1.MetricsResponse\x12W\n" +
	"\fStreamEvents\x12!.rightsizer.v1.EventStreamRequest\x1a\".rightsizer.v1.EventStreamResponse0\x01\x12L\n" +
	"\rExecuteAction\x12\x1c.rightsizer.v1.ActionRequest\x1a\x1d.rightsizer.v1.ActionResponse\x12Z\n" +
	"\x0fGetActionStatus\x12\".rightsizer.v1.ActionStatusRequest\x1a#.rightsizer.v1.ActionStatusResponse\x12D\n" +
	"\vHealthCheck\x12\x16.google.protobuf.Empty\x1a\x1d.rightsizer.v1.HealthResponseB\x1cZ\x1aright-sizer/api/grpc/v1;pbb\x06proto3"

var (
	file_api_grpc_v1_rightsizer_proto_rawDescOnce sync.Once
	file_api_grpc_v1_rightsizer_proto_rawDescData []byte
)

func file_api_grpc_v1_rightsizer_proto_rawDescGZIP() []byte {
	file_api_grpc_v1_rightsizer_proto_rawDescOnce.Do(func() {
		file_api_grpc_v1_rightsizer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_grpc_v1_rightsizer_proto_rawDesc), len(file_api_grpc_v1_rightsizer_proto_rawDesc)))
	})
	return file_api_grpc_v1_rightsizer_proto_rawDescData
}

var file_api_grpc_v1_rightsizer_proto_enumTypes = make([]protoimpl.EnumInfo, 8)
var file_api_grpc_v1_rightsizer_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_grpc_v1_rightsizer_proto_goTypes = []any{
	(ClusterStatus)(0),            // 0: rightsizer.v1.ClusterStatus
	(MetricType)(0),               // 1: rightsizer.v1.MetricType
	(EventType)(0),                // 2: rightsizer.v1.EventType
	(Severity)(0),                 // 3: rightsizer.v1.Severity
	(ActionStatus)(0),             // 4: rightsizer.v1.ActionStatus
	(RiskLevel)(0),                // 5: rightsizer.v1.RiskLevel
	(Priority)(0),                 // 6: rightsizer.v1.Priority
	(HealthStatus)(0),             // 7: rightsizer.v1.HealthStatus
	(*ClusterInfo)(nil),           // 8: rightsizer.v1.ClusterInfo
	(*MetricsRequest)(nil),        // 9: rightsizer.v1.MetricsRequest
	(*MetricsResponse)(nil),       // 10: rightsizer.v1.MetricsResponse
	(*Metric)(nil),                // 11: rightsizer.v1.Metric
	(*EventStreamRequest)(nil),    // 12: rightsizer.v1.EventStreamRequest
	(*EventStreamResponse)(nil),   // 13: rightsizer.v1.EventStreamResponse
	(*Event)(nil),                 // 14: rightsizer.v1.Event
	(*ActionRequest)(nil),         // 15: rightsizer.v1.ActionRequest
	(*ActionResponse)(nil),        // 16: rightsizer.v1.ActionResponse
	(*ActionStatusRequest)(nil),   // 17: rightsizer.v1.ActionStatusRequest
	(*ActionStatusResponse)(nil),  // 18: rightsizer.v1.ActionStatusResponse
	(*Action)(nil),                // 19: rightsizer.v1.Action
	(*ActionTarget)(nil),          // 20: rightsizer.v1.ActionTarget
	(*HealthResponse)(nil),        // 21: rightsizer.v1.HealthResponse
	nil,                           // 22: rightsizer.v1.Metric.LabelsEntry
	nil,                           // 23: rightsizer.v1.Event.DetailsEntry
	nil,                           // 24: rightsizer.v1.Action.ParametersEntry
	nil,                           // 25: rightsizer.v1.HealthResponse.ChecksEntry
	(*timestamppb.Timestamp)(nil), // 26: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 27: google.protobuf.Empty
}
var file_api_grpc_v1_rightsizer_proto_depIdxs = []int32{
	0,  // 0: rightsizer.v1.ClusterInfo.status:type_name -> rightsizer.v1.ClusterStatus
	1,  // 1: rightsizer.v1.MetricsRequest.type:type_name -> rightsizer.v1.MetricType
	26, // 2: rightsizer.v1.MetricsRequest.since:type_name -> google.protobuf.Timestamp
	11, // 3: rightsizer.v1.MetricsResponse.metrics:type_name -> rightsizer.v1.Metric
	26, // 4: rightsizer.v1.MetricsResponse.timestamp:type_name -> google.protobuf.Timestamp
	26, // 5: rightsizer.v1.Metric.timestamp:type_name -> google.protobuf.Timestamp
	22, // 6: rightsizer.v1.Metric.labels:type_name -> rightsizer.v1.Metric.LabelsEntry
	2,  // 7: rightsizer.v1.EventStreamRequest.event_types:type_name -> rightsizer.v1.EventType
	3,  // 8: rightsizer.v1.EventStreamRequest.severities:type_name -> rightsizer.v1.Severity
	14, // 9: rightsizer.v1.EventStreamResponse.event:type_name -> rightsizer.v1.Event
	3,  // 10: rightsizer.v1.Event.severity:type_name -> rightsizer.v1.Severity
	26, // 11: rightsizer.v1.Event.timestamp:type_name -> google.protobuf.Timestamp
	23, // 12: rightsizer.v1.Event.details:type_name -> rightsizer.v1.Event.DetailsEntry
	19, // 13: rightsizer.v1.ActionRequest.action:type_name -> rightsizer.v1.Action
	4,  // 14: rightsizer.v1.ActionStatusResponse.status:type_name -> rightsizer.v1.ActionStatus
	26, // 15: rightsizer.v1.ActionStatusResponse.updated_at:type_name -> google.protobuf.Timestamp
	20, // 16: rightsizer.v1.Action.target:type_name -> rightsizer.v1.ActionTarget
	24, // 17: rightsizer.v1.Action.parameters:type_name -> rightsizer.v1.Action.ParametersEntry
	5,  // 18: rightsizer.v1.Action.risk:type_name -> rightsizer.v1.RiskLevel
	6,  // 19: rightsizer.v1.Action.priority:type_name -> rightsizer.v1.Priority
	7,  // 20: rightsizer.v1.HealthResponse.status:type_name -> rightsizer.v1.HealthStatus
	25, // 21: rightsizer.v1.HealthResponse.checks:type_name -> rightsizer.v1.HealthResponse.ChecksEntry
	7,  // 22: rightsizer.v1.HealthResponse.ChecksEntry.value:type_name -> rightsizer.v1.HealthStatus
	27, // 23: rightsizer.v1.RightSizerService.GetClusterInfo:input_type -> google.protobuf.Empty
	9,  // 24: rightsizer.v1.RightSizerService.GetMetrics:input_type -> rightsizer.v1.MetricsRequest
	12, // 25: rightsizer.v1.RightSizerService.StreamEvents:input_type -> rightsizer.v1.EventStreamRequest
	15, // 26: rightsizer.v1.RightSizerService.ExecuteAction:input_type -> rightsizer.v1.ActionRequest
	17, // 27: rightsizer.v1.RightSizerService.GetActionStatus:input_type -> rightsizer.v1.ActionStatusRequest
	27, // 28: rightsizer.v1.RightSizerService.HealthCheck:input_type -> google.protobuf.Empty
	8,  // 29: rightsizer.v1.RightSizerService.GetClusterInfo:output_type -> rightsizer.v1.ClusterInfo
	10, // 30: rightsizer.v1.RightSizerService.GetMetrics:output_type -> rightsizer.v1.MetricsResponse
	13, // 31: rightsizer.v1.RightSizerService.StreamEvents:output_type -> rightsizer.v1.EventStreamResponse
	16, // 32: rightsizer.v1.RightSizerService.ExecuteAction:output_type -> rightsizer.v1.ActionResponse
	18, // 33: rightsizer.v1.RightSizerService.GetActionStatus:output_type -> rightsizer.v1.ActionStatusResponse
	21, // 34: rightsizer.v1.RightSizerService.HealthCheck:output_type -> rightsizer.v1.HealthResponse
	29, // [29:35] is the sub-list for method output_type
	23, // [23:29] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_api_grpc_v1_rightsizer_proto_init() }
func file_api_grpc_v1_rightsizer_proto_init() {
	if File_api_grpc_v1_rightsizer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_grpc_v1_rightsizer_proto_rawDesc), len(file_api_grpc_v1_rightsizer_proto_rawDesc)),
			NumEnums:      8,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_v1_rightsizer_proto_goTypes,
		DependencyIndexes: file_api_grpc_v1_rightsizer_proto_depIdxs,
		EnumInfos:         file_api_grpc_v1_rightsizer_proto_enumTypes,
		MessageInfos:      file_api_grpc_v1_rightsizer_proto_msgTypes,
	}.Build()
	File_api_grpc_v1_rightsizer_proto = out.File
	file_api_grpc_v1_rightsizer_proto_goTypes = nil
	file_api_grpc_v1_rightsizer_proto_depIdxs = nil
}
