apiVersion: apps/v1
kind: Deployment
metadata:
  name: right-sizer
  namespace: default
  labels:
    app: right-sizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: right-sizer
  template:
    metadata:
      labels:
        app: right-sizer
    spec:
      serviceAccountName: right-sizer
      containers:
        - name: right-sizer
          image: right-sizer:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ENABLE_INPLACE_RESIZE
              value: "true"
            - name: RESIZE_INTERVAL
              value: "60s"
            - name: PROMETHEUS_URL
              value: "http://prometheus:9090"
            - name: METRICS_PROVIDER
              value: "kubernetes" # Use kubernetes metrics-server instead of prometheus
            - name: LOG_LEVEL
              value: "info"
            - name: RESIZE_INTERVAL
              value: "30s" # How often to check and resize (e.g., 30s, 1m, 5m)
            # Resource sizing configuration
            - name: CPU_REQUEST_MULTIPLIER
              value: "1.2" # Multiply usage by this to get request
            - name: MEMORY_REQUEST_MULTIPLIER
              value: "1.2" # Multiply usage by this to get request
            - name: CPU_LIMIT_MULTIPLIER
              value: "2.0" # Multiply request by this to get limit
            - name: MEMORY_LIMIT_MULTIPLIER
              value: "2.0" # Multiply request by this to get limit
            - name: MAX_CPU_LIMIT
              value: "4000" # Maximum CPU limit in millicores (4 cores)
            - name: MAX_MEMORY_LIMIT
              value: "8192" # Maximum memory limit in MB (8GB)
            - name: MIN_CPU_REQUEST
              value: "10" # Minimum CPU request in millicores
            - name: MIN_MEMORY_REQUEST
              value: "64" # Minimum memory request in MB
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 8080
              name: metrics
            - containerPort: 8081
              name: health
