apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rightsizerconfigs.rightsizer.io
spec:
  group: rightsizer.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                enabled:
                  type: boolean
                  default: true
                defaultMode:
                  type: string
                  enum: ["aggressive", "balanced", "conservative", "custom"]
                  default: "balanced"
                resizeInterval:
                  type: string
                  default: "30s"
                dryRun:
                  type: boolean
                  default: false
                defaultResourceStrategy:
                  type: object
                  properties:
                    cpu:
                      type: object
                      properties:
                        requestMultiplier:
                          type: number
                        limitMultiplier:
                          type: number
                        minRequest:
                          type: string
                        maxLimit:
                          type: string
                        scaleUpThreshold:
                          type: number
                        scaleDownThreshold:
                          type: number
                    memory:
                      type: object
                      properties:
                        requestMultiplier:
                          type: number
                        limitMultiplier:
                          type: number
                        minRequest:
                          type: string
                        maxLimit:
                          type: string
                        scaleUpThreshold:
                          type: number
                        scaleDownThreshold:
                          type: number
                globalConstraints:
                  type: object
                  properties:
                    maxChangePercentage:
                      type: integer
                    minChangeThreshold:
                      type: integer
                    maxMemoryGB:
                      type: integer
                    maxCPUCores:
                      type: integer
                    preventOOMKill:
                      type: boolean
                    respectPodDisruptionBudget:
                      type: boolean
                metricsConfig:
                  type: object
                  properties:
                    provider:
                      type: string
                    scrapeInterval:
                      type: string
                    historyRetention:
                      type: string
                    aggregationMethod:
                      type: string
                    includeCustomMetrics:
                      type: boolean
                namespaceConfig:
                  type: object
                  properties:
                    includeNamespaces:
                      type: array
                      items:
                        type: string
                    excludeNamespaces:
                      type: array
                      items:
                        type: string
                    systemNamespaces:
                      type: array
                      items:
                        type: string
                notificationConfig:
                  type: object
                  properties:
                    enableNotifications:
                      type: boolean
                observabilityConfig:
                  type: object
                  properties:
                    logLevel:
                      type: string
                    logFormat:
                      type: string
                    enableAuditLogging:
                      type: boolean
                    enableMetricsExport:
                      type: boolean
                    metricsPort:
                      type: integer
                    enableTracing:
                      type: boolean
                    enableProfiling:
                      type: boolean
                    profilingPort:
                      type: integer
                operatorConfig:
                  type: object
                  properties:
                    leaderElection:
                      type: boolean
                    leaderElectionNamespace:
                      type: string
                    leaderElectionID:
                      type: string
                    maxConcurrentReconciles:
                      type: integer
                    workerThreads:
                      type: integer
                    qps:
                      type: integer
                    burst:
                      type: integer
                    retryAttempts:
                      type: integer
                    retryInterval:
                      type: string
                    healthProbePort:
                      type: integer
                    readinessEndpoint:
                      type: string
                    livenessEndpoint:
                      type: string
                securityConfig:
                  type: object
                  properties:
                    enableAdmissionController:
                      type: boolean
                    admissionWebhookPort:
                      type: integer
                    requireAnnotation:
                      type: boolean
                    annotationKey:
                      type: string
                    enableMutatingWebhook:
                      type: boolean
                    enableValidatingWebhook:
                      type: boolean
                    tlsCertDir:
                      type: string
                    webhookTimeoutSeconds:
                      type: integer
                podSelectionConfig:
                  type: object
                  properties:
                    excludedPodPhases:
                      type: array
                      items:
                        type: string
                        enum:
                          [
                            "Pending",
                            "Running",
                            "Succeeded",
                            "Failed",
                            "Unknown",
                          ]
                      default: ["Pending"]
                    excludeTerminatingPods:
                      type: boolean
                      default: true
                    includeLabelSelectors:
                      type: array
                      items:
                        type: object
                        properties:
                          matchLabels:
                            type: object
                            additionalProperties:
                              type: string
                          matchExpressions:
                            type: array
                            items:
                              type: object
                              properties:
                                key:
                                  type: string
                                operator:
                                  type: string
                                  enum:
                                    ["In", "NotIn", "Exists", "DoesNotExist"]
                                values:
                                  type: array
                                  items:
                                    type: string
                    excludeLabelSelectors:
                      type: array
                      items:
                        type: object
                        properties:
                          matchLabels:
                            type: object
                            additionalProperties:
                              type: string
                          matchExpressions:
                            type: array
                            items:
                              type: object
                              properties:
                                key:
                                  type: string
                                operator:
                                  type: string
                                  enum:
                                    ["In", "NotIn", "Exists", "DoesNotExist"]
                                values:
                                  type: array
                                  items:
                                    type: string
                    minPodAge:
                      type: string
                      default: "5m"
                    excludeControllerTypes:
                      type: array
                      items:
                        type: string
                      default: ["Job", "CronJob"]
            status:
              type: object
              properties:
                phase:
                  type: string
                lastAppliedTime:
                  type: string
                activePolicies:
                  type: integer
                operatorVersion:
                  type: string
                observedGeneration:
                  type: integer
                message:
                  type: string
                systemHealth:
                  type: object
                  properties:
                    healthy:
                      type: boolean
                    isLeader:
                      type: boolean
                    lastHealthCheck:
                      type: string
                    metricsProviderHealthy:
                      type: boolean
                    components:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          status:
                            type: string
                          message:
                            type: string
      subresources:
        status: {}
  scope: Cluster
  names:
    plural: rightsizerconfigs
    singular: rightsizerconfig
    kind: RightSizerConfig
    shortNames:
      - rsc
