apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rightsizerpolicies.rightsizer.io
spec:
  group: rightsizer.io
  names:
    kind: RightSizerPolicy
    listKind: RightSizerPolicyList
    plural: rightsizerpolicies
    singular: rightsizerpolicy
    shortNames:
      - rsp
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                enabled:
                  type: boolean
                  default: true
                priority:
                  type: integer
                  minimum: 0
                  maximum: 1000
                  default: 100
                mode:
                  type: string
                  enum: ["aggressive", "balanced", "conservative", "custom"]
                  default: balanced
                dryRun:
                  type: boolean
                  default: false
                targetRef:
                  type: object
                  properties:
                    kind:
                      type: string
                      enum: ["Deployment", "StatefulSet", "DaemonSet", "Pod", "ReplicaSet", "Job", "CronJob"]
                    apiVersion:
                      type: string
                      default: "apps/v1"
                    namespaces:
                      type: array
                      items:
                        type: string
                    excludeNamespaces:
                      type: array
                      items:
                        type: string
                    labelSelector:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    annotationSelector:
                      type: object
                      additionalProperties:
                        type: string
                    names:
                      type: array
                      items:
                        type: string
                    excludeNames:
                      type: array
                      items:
                        type: string
                resourceStrategy:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                schedule:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                constraints:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                webhooks:
                  type: array
                  items:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                resourceAnnotations:
                  type: object
                  additionalProperties:
                    type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
