apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rightsizerpolicies.rightsizer.io
spec:
  group: rightsizer.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              enabled:
                type: boolean
                default: true
              priority:
                type: integer
                minimum: 0
                maximum: 1000
                default: 100
              mode:
                type: string
                enum: ["aggressive", "balanced", "conservative", "custom"]
                default: "balanced"
              dryRun:
                type: boolean
                default: false
              targetRef:
                type: object
                properties:
                  kind:
                    type: string
                    enum: ["Deployment", "StatefulSet", "DaemonSet", "Pod", "ReplicaSet", "Job", "CronJob"]
                  apiVersion:
                    type: string
                    default: "apps/v1"
                  namespaces:
                    type: array
                    items:
                      type: string
                  excludeNamespaces:
                    type: array
                    items:
                      type: string
                  labelSelector:
                    type: object
                    properties:
                      matchLabels:
                        type: object
                        additionalProperties:
                          type: string
                      matchExpressions:
                        type: array
                        items:
                          type: object
                          properties:
                            key:
                              type: string
                            operator:
                              type: string
                            values:
                              type: array
                              items:
                                type: string
                  names:
                    type: array
                    items:
                      type: string
                  excludeNames:
                    type: array
                    items:
                      type: string
              resourceStrategy:
                type: object
                properties:
                  cpu:
                    type: object
                    properties:
                      requestMultiplier:
                        type: number
                        minimum: 0.1
                        maximum: 10
                      requestAddition:
                        type: integer
                        minimum: 0
                      limitMultiplier:
                        type: number
                        minimum: 0.1
                        maximum: 10
                      limitAddition:
                        type: integer
                        minimum: 0
                      minRequest:
                        type: integer
                        minimum: 0
                      maxLimit:
                        type: integer
                        minimum: 0
                      targetUtilization:
                        type: integer
                        minimum: 0
                        maximum: 100
                  memory:
                    type: object
                    properties:
                      requestMultiplier:
                        type: number
                        minimum: 0.1
                        maximum: 10
                      requestAddition:
                        type: integer
                        minimum: 0
                      limitMultiplier:
                        type: number
                        minimum: 0.1
                        maximum: 10
                      limitAddition:
                        type: integer
                        minimum: 0
                      minRequest:
                        type: integer
                        minimum: 0
                      maxLimit:
                        type: integer
                        minimum: 0
                      targetUtilization:
                        type: integer
                        minimum: 0
                        maximum: 100
                  metricsSource:
                    type: string
                    enum: ["metrics-server", "prometheus", "custom"]
                    default: "metrics-server"
                  historyWindow:
                    type: string
                    default: "7d"
                  percentile:
                    type: integer
                    enum: [50, 90, 95, 99]
                    default: 95
                  updateMode:
                    type: string
                    enum: ["immediate", "rolling", "scheduled"]
                    default: "rolling"
              constraints:
                type: object
                properties:
                  maxChangePercentage:
                    type: integer
                    minimum: 0
                    maximum: 100
                  minChangeThreshold:
                    type: integer
                    minimum: 0
                    maximum: 100
                  cooldownPeriod:
                    type: string
                    default: "5m"
                  respectPDB:
                    type: boolean
                    default: true
                  respectHPA:
                    type: boolean
                    default: true
                  respectVPA:
                    type: boolean
                    default: true
          status:
            type: object
            properties:
              phase:
                type: string
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
              lastAppliedTime:
                type: string
              lastEvaluationTime:
                type: string
              resourcesAffected:
                type: integer
              resourcesResized:
                type: integer
              totalSavings:
                type: object
                properties:
                  cpuSaved:
                    type: integer
                  memorySaved:
                    type: integer
                  costSaved:
                    type: string
              observedGeneration:
                type: integer
              message:
                type: string
              metrics:
                type: object
                properties:
                  averageCPUUtilization:
                    type: integer
                  averageMemoryUtilization:
                    type: integer
                  totalCPURequests:
                    type: integer
                  totalMemoryRequests:
                    type: integer
                  lastUpdated:
                    type: string
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Enabled
      type: boolean
      jsonPath: .spec.enabled
    - name: Mode
      type: string
      jsonPath: .spec.mode
    - name: Status
      type: string
      jsonPath: .status.phase
    - name: Last Applied
      type: date
      jsonPath: .status.lastAppliedTime
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: rightsizerpolicies
    singular: rightsizerpolicy
    kind: RightSizerPolicy
    shortNames:
    - rsp
